import java.util.ArrayList;
import java.util.List;

public class County{
	
	
	public static void main(String[] args) {
		String[] unrCt = getUnrepeatedCounties();
		String[] allCt = getAllCounties();
		
		List<String> unrCtList = new ArrayList<>();
		List<String> allCtList = new ArrayList<>();
		List<String> countiesDontExist = new ArrayList<>();
		
//		for (String unr : unrCt) {
//			unrCtList.add(unr);
//		}
		
		for (String all : allCt) {
			allCtList.add(all);
		}
		
		int count=0;
		for (String unr : unrCt) {
			if (allCtList.contains(unr)) {
				count++;
			} else {
				countiesDontExist.add(unr);
			}
		}
		System.out.println(unrCt.length);
		System.out.println(allCt.length);
		System.out.println(count);
		System.out.println(countiesDontExist.size());
		
		System.out.println(countiesDontExist);
		
		
	}
	
	public static String[] getUnrepeatedCounties() {
		
	
	String unrepeatedCounties = "Hampden\n" + 
			"Hampshire\n" + 
			"Worcester\n" + 
			"Berkshire\n" + 
			"Franklin\n" + 
			"Middlesex\n" + 
			"Essex\n" + 
			"Norfolk\n" + 
			"Plymouth\n" + 
			"Bristol\n" + 
			"Suffolk\n" + 
			"Barnstable\n" + 
			"Dukes\n" + 
			"Nantucket\n" + 
			"Providence\n" + 
			"Washington\n" + 
			"Kent\n" + 
			"Newport\n" + 
			"Hillsborough\n" + 
			"Rockingham\n" + 
			"Merrimack\n" + 
			"Grafton\n" + 
			"Belknap\n" + 
			"Carroll\n" + 
			"Sullivan\n" + 
			"Cheshire\n" + 
			"Coos\n" + 
			"Strafford\n" + 
			"York\n" + 
			"Cumberland\n" + 
			"Sagadahoc\n" + 
			"Oxford\n" + 
			"Androscoggin\n" + 
			"Kennebec\n" + 
			"Lincoln\n" + 
			"Waldo\n" + 
			"Penobscot\n" + 
			"Piscataquis\n" + 
			"Hancock\n" + 
			"Aroostook\n" + 
			"Somerset\n" + 
			"Knox\n" + 
			"Windsor\n" + 
			"Orange\n" + 
			"Caledonia\n" + 
			"Windham\n" + 
			"Bennington\n" + 
			"Chittenden\n" + 
			"Grand Isle\n" + 
			"Lamoille\n" + 
			"Addison\n" + 
			"Rutland\n" + 
			"Orleans\n" + 
			"Hartford\n" + 
			"Litchfield\n" + 
			"Tolland\n" + 
			"New London\n" + 
			"New Haven\n" + 
			"Fairfield\n" + 
			"Hudson\n" + 
			"Morris\n" + 
			"Bergen\n" + 
			"Passaic\n" + 
			"Union\n" + 
			"Sussex\n" + 
			"Monmouth\n" + 
			"Warren\n" + 
			"Hunterdon\n" + 
			"Salem\n" + 
			"Camden\n" + 
			"Ocean\n" + 
			"Burlington\n" + 
			"Gloucester\n" + 
			"Atlantic\n" + 
			"Cape May\n" + 
			"Mercer\n" + 
			"New York\n" + 
			"Richmond\n" + 
			"Bronx\n" + 
			"Westchester\n" + 
			"Putnam\n" + 
			"Rockland\n" + 
			"Nassau\n" + 
			"Queens\n" + 
			"Kings\n" + 
			"Albany\n" + 
			"Schenectady\n" + 
			"Montgomery\n" + 
			"Greene\n" + 
			"Columbia\n" + 
			"Rensselaer\n" + 
			"Saratoga\n" + 
			"Fulton\n" + 
			"Schoharie\n" + 
			"Otsego\n" + 
			"Hamilton\n" + 
			"Delaware\n" + 
			"Ulster\n" + 
			"Dutchess\n" + 
			"Clinton\n" + 
			"St. Lawrence\n" + 
			"Onondaga\n" + 
			"Cayuga\n" + 
			"Oswego\n" + 
			"Madison\n" + 
			"Cortland\n" + 
			"Tompkins\n" + 
			"Oneida\n" + 
			"Chenango\n" + 
			"Wayne\n" + 
			"Seneca\n" + 
			"Lewis\n" + 
			"Herkimer\n" + 
			"Jefferson\n" + 
			"Tioga\n" + 
			"Broome\n" + 
			"Erie\n" + 
			"Genesee\n" + 
			"Niagara\n" + 
			"Wyoming\n" + 
			"Cattaraugus\n" + 
			"Chautauqua\n" + 
			"Livingston\n" + 
			"Yates\n" + 
			"Monroe\n" + 
			"Ontario\n" + 
			"Steuben\n" + 
			"Allegany\n" + 
			"Schuyler\n" + 
			"Chemung\n" + 
			"Beaver\n" + 
			"Allegheny\n" + 
			"Westmoreland\n" + 
			"Fayette\n" + 
			"Bedford\n" + 
			"Armstrong\n" + 
			"Indiana\n" + 
			"Cambria\n" + 
			"Clearfield\n" + 
			"Elk\n" + 
			"Cameron\n" + 
			"Butler\n" + 
			"Clarion\n" + 
			"Lawrence\n" + 
			"Crawford\n" + 
			"Forest\n" + 
			"Venango\n" + 
			"McKean\n" + 
			"Blair\n" + 
			"Huntingdon\n" + 
			"Centre\n" + 
			"Potter\n" + 
			"Bradford\n" + 
			"Mifflin\n" + 
			"Lebanon\n" + 
			"Dauphin\n" + 
			"Perry\n" + 
			"Northumberland\n" + 
			"Lancaster\n" + 
			"Juniata\n" + 
			"Snyder\n" + 
			"Adams\n" + 
			"Lycoming\n" + 
			"Montour\n" + 
			"Schuylkill\n" + 
			"Lehigh\n" + 
			"Northampton\n" + 
			"Carbon\n" + 
			"Berks\n" + 
			"Bucks\n" + 
			"Luzerne\n" + 
			"Pike\n" + 
			"Lackawanna\n" + 
			"Susquehanna\n" + 
			"Chester\n" + 
			"Philadelphia\n" + 
			"New Castle\n" + 
			"District of Columbia\n" + 
			"Loudoun\n" + 
			"Culpeper\n" + 
			"Prince William\n" + 
			"Manassas\n" + 
			"Fauquier\n" + 
			"Fairfax\n" + 
			"Clarke\n" + 
			"Charles\n" + 
			"St. Mary's\n" + 
			"Prince George's\n" + 
			"Calvert\n" + 
			"Howard\n" + 
			"Anne Arundel\n" + 
			"Harford\n" + 
			"Baltimore\n" + 
			"Garrett\n" + 
			"Talbot\n" + 
			"Queen Anne's\n" + 
			"Dorchester\n" + 
			"Caroline\n" + 
			"Frederick\n" + 
			"Wicomico\n" + 
			"Cecil\n" + 
			"Falls Church\n" + 
			"Arlington\n" + 
			"Alexandria\n" + 
			"Fredericksburg\n" + 
			"Stafford\n" + 
			"Spotsylvania\n" + 
			"King George\n" + 
			"Winchester\n" + 
			"Rappahannock\n" + 
			"Shenandoah\n" + 
			"Page\n" + 
			"Harrisonburg\n" + 
			"Augusta\n" + 
			"Albemarle\n" + 
			"Charlottesville\n" + 
			"Nelson\n" + 
			"Fluvanna\n" + 
			"Waynesboro\n" + 
			"Amelia\n" + 
			"Buckingham\n" + 
			"Hanover\n" + 
			"King William\n" + 
			"New Kent\n" + 
			"Mathews\n" + 
			"King and Queen\n" + 
			"Louisa\n" + 
			"Charles City\n" + 
			"Goochland\n" + 
			"Henrico\n" + 
			"Chesterfield\n" + 
			"Powhatan\n" + 
			"James City\n" + 
			"Williamsburg\n" + 
			"Accomack\n" + 
			"Isle of Wight\n" + 
			"Chesapeake\n" + 
			"Virginia Beach\n" + 
			"Newport News\n" + 
			"Hampton\n" + 
			"Poquoson\n" + 
			"Portsmouth\n" + 
			"Prince George\n" + 
			"Petersburg\n" + 
			"Dinwiddie\n" + 
			"Brunswick\n" + 
			"Nottoway\n" + 
			"Southampton\n" + 
			"Colonial Heights\n" + 
			"Surry\n" + 
			"Greensville\n" + 
			"Hopewell\n" + 
			"Prince Edward\n" + 
			"Mecklenburg\n" + 
			"Charlotte\n" + 
			"Lunenburg\n" + 
			"Roanoke\n" + 
			"Patrick\n" + 
			"Henry\n" + 
			"Pulaski\n" + 
			"Botetourt\n" + 
			"Pittsylvania\n" + 
			"Floyd\n" + 
			"Giles\n" + 
			"Craig\n" + 
			"Radford\n" + 
			"Wise\n" + 
			"Dickenson\n" + 
			"Lee\n" + 
			"Russell\n" + 
			"Buchanan\n" + 
			"Scott\n" + 
			"Norton\n" + 
			"Grayson\n" + 
			"Smyth\n" + 
			"Wythe\n" + 
			"Bland\n" + 
			"Tazewell\n" + 
			"Galax\n" + 
			"Staunton\n" + 
			"Bath\n" + 
			"Highland\n" + 
			"Rockbridge\n" + 
			"Buena Vista\n" + 
			"Alleghany\n" + 
			"Lynchburg\n" + 
			"Campbell\n" + 
			"Halifax\n" + 
			"Amherst\n" + 
			"Appomattox\n" + 
			"Danville\n" + 
			"McDowell\n" + 
			"Mingo\n" + 
			"Greenbrier\n" + 
			"Pocahontas\n" + 
			"Summers\n" + 
			"Roane\n" + 
			"Raleigh\n" + 
			"Boone\n" + 
			"Kanawha\n" + 
			"Clay\n" + 
			"Logan\n" + 
			"Braxton\n" + 
			"Mason\n" + 
			"Calhoun\n" + 
			"Jackson\n" + 
			"Gilmer\n" + 
			"Berkeley\n" + 
			"Morgan\n" + 
			"Cabell\n" + 
			"Ohio\n" + 
			"Brooke\n" + 
			"Marshall\n" + 
			"Wood\n" + 
			"Pleasants\n" + 
			"Wirt\n" + 
			"Tyler\n" + 
			"Ritchie\n" + 
			"Wetzel\n" + 
			"Upshur\n" + 
			"Nicholas\n" + 
			"Webster\n" + 
			"Randolph\n" + 
			"Barbour\n" + 
			"Tucker\n" + 
			"Harrison\n" + 
			"Doddridge\n" + 
			"Taylor\n" + 
			"Preston\n" + 
			"Monongalia\n" + 
			"Marion\n" + 
			"Grant\n" + 
			"Mineral\n" + 
			"Hardy\n" + 
			"Pendleton\n" + 
			"Davie\n" + 
			"Forsyth\n" + 
			"Yadkin\n" + 
			"Rowan\n" + 
			"Stokes\n" + 
			"Alamance\n" + 
			"Chatham\n" + 
			"Caswell\n" + 
			"Guilford\n" + 
			"Davidson\n" + 
			"Moore\n" + 
			"Person\n" + 
			"Harnett\n" + 
			"Wake\n" + 
			"Durham\n" + 
			"Johnston\n" + 
			"Granville\n" + 
			"Vance\n" + 
			"Nash\n" + 
			"Edgecombe\n" + 
			"Hertford\n" + 
			"Beaufort\n" + 
			"Pitt\n" + 
			"Wilson\n" + 
			"Hyde\n" + 
			"Martin\n" + 
			"Bertie\n" + 
			"Pasquotank\n" + 
			"Dare\n" + 
			"Currituck\n" + 
			"Perquimans\n" + 
			"Tyrrell\n" + 
			"Gates\n" + 
			"Chowan\n" + 
			"Stanly\n" + 
			"Gaston\n" + 
			"Anson\n" + 
			"Cleveland\n" + 
			"Rutherford\n" + 
			"Cabarrus\n" + 
			"Iredell\n" + 
			"Sampson\n" + 
			"Bladen\n" + 
			"Duplin\n" + 
			"Robeson\n" + 
			"Scotland\n" + 
			"Hoke\n" + 
			"New Hanover\n" + 
			"Pender\n" + 
			"Columbus\n" + 
			"Onslow\n" + 
			"Lenoir\n" + 
			"Pamlico\n" + 
			"Carteret\n" + 
			"Craven\n" + 
			"Jones\n" + 
			"Catawba\n" + 
			"Watauga\n" + 
			"Wilkes\n" + 
			"Caldwell\n" + 
			"Burke\n" + 
			"Ashe\n" + 
			"Avery\n" + 
			"Alexander\n" + 
			"Buncombe\n" + 
			"Graham\n" + 
			"Mitchell\n" + 
			"Transylvania\n" + 
			"Swain\n" + 
			"Yancey\n" + 
			"Haywood\n" + 
			"Polk\n" + 
			"Henderson\n" + 
			"Macon\n" + 
			"Cherokee\n" + 
			"Clarendon\n" + 
			"Bamberg\n" + 
			"Lexington\n" + 
			"Kershaw\n" + 
			"Richland\n" + 
			"Orangeburg\n" + 
			"Newberry\n" + 
			"Sumter\n" + 
			"Darlington\n" + 
			"Colleton\n" + 
			"Aiken\n" + 
			"Florence\n" + 
			"Saluda\n" + 
			"Spartanburg\n" + 
			"Laurens\n" + 
			"Charleston\n" + 
			"Georgetown\n" + 
			"Horry\n" + 
			"Marlboro\n" + 
			"Dillon\n" + 
			"Greenville\n" + 
			"Abbeville\n" + 
			"Anderson\n" + 
			"Pickens\n" + 
			"Oconee\n" + 
			"Greenwood\n" + 
			"Allendale\n" + 
			"Barnwell\n" + 
			"McCormick\n" + 
			"Edgefield\n" + 
			"Jasper\n" + 
			"DeKalb\n" + 
			"Cobb\n" + 
			"Barrow\n" + 
			"Rockdale\n" + 
			"Newton\n" + 
			"Gwinnett\n" + 
			"Walton\n" + 
			"Bartow\n" + 
			"Haralson\n" + 
			"Douglas\n" + 
			"Paulding\n" + 
			"Lamar\n" + 
			"Butts\n" + 
			"Heard\n" + 
			"Meriwether\n" + 
			"Coweta\n" + 
			"Spalding\n" + 
			"Troup\n" + 
			"Clayton\n" + 
			"Upson\n" + 
			"Emanuel\n" + 
			"Wheeler\n" + 
			"Bulloch\n" + 
			"Evans\n" + 
			"Tattnall\n" + 
			"Toombs\n" + 
			"Candler\n" + 
			"Jenkins\n" + 
			"Screven\n" + 
			"Treutlen\n" + 
			"Hall\n" + 
			"Habersham\n" + 
			"Banks\n" + 
			"Fannin\n" + 
			"Hart\n" + 
			"Rabun\n" + 
			"White\n" + 
			"Lumpkin\n" + 
			"Dawson\n" + 
			"Stephens\n" + 
			"Towns\n" + 
			"Oglethorpe\n" + 
			"Elbert\n" + 
			"Taliaferro\n" + 
			"Gordon\n" + 
			"Murray\n" + 
			"Walker\n" + 
			"Whitfield\n" + 
			"Catoosa\n" + 
			"Chattooga\n" + 
			"Dade\n" + 
			"McDuffie\n" + 
			"Glascock\n" + 
			"Wilcox\n" + 
			"Wilkinson\n" + 
			"Houston\n" + 
			"Dooly\n" + 
			"Peach\n" + 
			"Dodge\n" + 
			"Bleckley\n" + 
			"Crisp\n" + 
			"Twiggs\n" + 
			"Johnson\n" + 
			"Bibb\n" + 
			"Telfair\n" + 
			"Baldwin\n" + 
			"Liberty\n" + 
			"Effingham\n" + 
			"McIntosh\n" + 
			"Bryan\n" + 
			"Long\n" + 
			"Ware\n" + 
			"Bacon\n" + 
			"Coffee\n" + 
			"Appling\n" + 
			"Pierce\n" + 
			"Glynn\n" + 
			"Jeff Davis\n" + 
			"Charlton\n" + 
			"Brantley\n" + 
			"Lowndes\n" + 
			"Cook\n" + 
			"Berrien\n" + 
			"Clinch\n" + 
			"Atkinson\n" + 
			"Brooks\n" + 
			"Thomas\n" + 
			"Lanier\n" + 
			"Colquitt\n" + 
			"Echols\n" + 
			"Dougherty\n" + 
			"Turner\n" + 
			"Tift\n" + 
			"Ben Hill\n" + 
			"Worth\n" + 
			"Irwin\n" + 
			"Harris\n" + 
			"Chattahoochee\n" + 
			"Schley\n" + 
			"Stewart\n" + 
			"Muscogee\n" + 
			"Suwannee\n" + 
			"St. Johns\n" + 
			"Baker\n" + 
			"Lafayette\n" + 
			"Lake\n" + 
			"Flagler\n" + 
			"Volusia\n" + 
			"Duval\n" + 
			"Leon\n" + 
			"Gadsden\n" + 
			"Wakulla\n" + 
			"Bay\n" + 
			"Holmes\n" + 
			"Gulf\n" + 
			"Escambia\n" + 
			"Santa Rosa\n" + 
			"Okaloosa\n" + 
			"Alachua\n" + 
			"Gilchrist\n" + 
			"Levy\n" + 
			"Dixie\n" + 
			"Seminole\n" + 
			"Brevard\n" + 
			"Indian River\n" + 
			"Broward\n" + 
			"Miami-Dade\n" + 
			"Palm Beach\n" + 
			"Hendry\n" + 
			"Glades\n" + 
			"Pasco\n" + 
			"Pinellas\n" + 
			"Highlands\n" + 
			"Hardee\n" + 
			"Osceola\n" + 
			"Collier\n" + 
			"Manatee\n" + 
			"Sarasota\n" + 
			"DeSoto\n" + 
			"Citrus\n" + 
			"Hernando\n" + 
			"St. Lucie\n" + 
			"Okeechobee\n" + 
			"St. Clair\n" + 
			"Shelby\n" + 
			"Tallapoosa\n" + 
			"Blount\n" + 
			"Talladega\n" + 
			"Cullman\n" + 
			"Chilton\n" + 
			"Coosa\n" + 
			"Tuscaloosa\n" + 
			"Hale\n" + 
			"Winston\n" + 
			"Lauderdale\n" + 
			"Limestone\n" + 
			"Colbert\n" + 
			"Etowah\n" + 
			"Autauga\n" + 
			"Crenshaw\n" + 
			"Elmore\n" + 
			"Covington\n" + 
			"Bullock\n" + 
			"Cleburne\n" + 
			"Geneva\n" + 
			"Dale\n" + 
			"Conecuh\n" + 
			"Mobile\n" + 
			"Dallas\n" + 
			"Marengo\n" + 
			"Chambers\n" + 
			"Choctaw\n" + 
			"Williamson\n" + 
			"Cheatham\n" + 
			"Cannon\n" + 
			"Sumner\n" + 
			"Hickman\n" + 
			"Dickson\n" + 
			"Smith\n" + 
			"Robertson\n" + 
			"Trousdale\n" + 
			"Humphreys\n" + 
			"Grundy\n" + 
			"McMinn\n" + 
			"Bradley\n" + 
			"Rhea\n" + 
			"Meigs\n" + 
			"Sequatchie\n" + 
			"Bledsoe\n" + 
			"Hawkins\n" + 
			"Carter\n" + 
			"Unicoi\n" + 
			"Grainger\n" + 
			"Cocke\n" + 
			"Claiborne\n" + 
			"Sevier\n" + 
			"Loudon\n" + 
			"Hamblen\n" + 
			"Crockett\n" + 
			"Tipton\n" + 
			"Dyer\n" + 
			"Hardeman\n" + 
			"Benton\n" + 
			"Weakley\n" + 
			"Obion\n" + 
			"Gibson\n" + 
			"McNairy\n" + 
			"Decatur\n" + 
			"Hardin\n" + 
			"Maury\n" + 
			"Fentress\n" + 
			"Overton\n" + 
			"Pickett\n" + 
			"Van Buren\n" + 
			"Panola\n" + 
			"Coahoma\n" + 
			"Tate\n" + 
			"Quitman\n" + 
			"Tippah\n" + 
			"Tunica\n" + 
			"Bolivar\n" + 
			"Issaquena\n" + 
			"Sharkey\n" + 
			"Sunflower\n" + 
			"Itawamba\n" + 
			"Tishomingo\n" + 
			"Prentiss\n" + 
			"Alcorn\n" + 
			"Pontotoc\n" + 
			"Chickasaw\n" + 
			"Grenada\n" + 
			"Tallahatchie\n" + 
			"Yalobusha\n" + 
			"Leflore\n" + 
			"Yazoo\n" + 
			"Hinds\n" + 
			"Rankin\n" + 
			"Simpson\n" + 
			"Leake\n" + 
			"Copiah\n" + 
			"Attala\n" + 
			"Jefferson Davis\n" + 
			"Kemper\n" + 
			"Noxubee\n" + 
			"Neshoba\n" + 
			"Forrest\n" + 
			"Pearl River\n" + 
			"Stone\n" + 
			"Amite\n" + 
			"Walthall\n" + 
			"Oktibbeha\n" + 
			"Early\n" + 
			"Terrell\n" + 
			"Grady\n" + 
			"Miller\n" + 
			"Trimble\n" + 
			"Oldham\n" + 
			"Spencer\n" + 
			"Bullitt\n" + 
			"Meade\n" + 
			"Breckinridge\n" + 
			"Powell\n" + 
			"Menifee\n" + 
			"Estill\n" + 
			"Jessamine\n" + 
			"Woodford\n" + 
			"Bourbon\n" + 
			"Owen\n" + 
			"Clark\n" + 
			"Rockcastle\n" + 
			"Boyle\n" + 
			"Garrard\n" + 
			"Whitley\n" + 
			"Laurel\n" + 
			"Harlan\n" + 
			"Bell\n" + 
			"Leslie\n" + 
			"Letcher\n" + 
			"Bracken\n" + 
			"Kenton\n" + 
			"Fleming\n" + 
			"Gallatin\n" + 
			"Boyd\n" + 
			"Greenup\n" + 
			"Elliott\n" + 
			"Wolfe\n" + 
			"Owsley\n" + 
			"Breathitt\n" + 
			"Magoffin\n" + 
			"Knott\n" + 
			"McCracken\n" + 
			"Calloway\n" + 
			"Carlisle\n" + 
			"Ballard\n" + 
			"Graves\n" + 
			"Crittenden\n" + 
			"Lyon\n" + 
			"Allen\n" + 
			"Barren\n" + 
			"Metcalfe\n" + 
			"Edmonson\n" + 
			"Todd\n" + 
			"Trigg\n" + 
			"Christian\n" + 
			"Daviess\n" + 
			"Muhlenberg\n" + 
			"McLean\n" + 
			"Hopkins\n" + 
			"Casey\n" + 
			"Adair\n" + 
			"McCreary\n" + 
			"Larue\n" + 
			"Green\n" + 
			"Licking\n" + 
			"Champaign\n" + 
			"Ross\n" + 
			"Pickaway\n" + 
			"Hocking\n" + 
			"Morrow\n" + 
			"Wyandot\n" + 
			"Sandusky\n" + 
			"Ottawa\n" + 
			"Lucas\n" + 
			"Williams\n" + 
			"Defiance\n" + 
			"Muskingum\n" + 
			"Noble\n" + 
			"Belmont\n" + 
			"Guernsey\n" + 
			"Coshocton\n" + 
			"Tuscarawas\n" + 
			"Columbiana\n" + 
			"Lorain\n" + 
			"Ashtabula\n" + 
			"Cuyahoga\n" + 
			"Geauga\n" + 
			"Summit\n" + 
			"Portage\n" + 
			"Medina\n" + 
			"Mahoning\n" + 
			"Trumbull\n" + 
			"Stark\n" + 
			"Ashland\n" + 
			"Huron\n" + 
			"Preble\n" + 
			"Brown\n" + 
			"Clermont\n" + 
			"Darke\n" + 
			"Miami\n" + 
			"Gallia\n" + 
			"Vinton\n" + 
			"Scioto\n" + 
			"Athens\n" + 
			"Auglaize\n" + 
			"Van Wert\n" + 
			"Hendricks\n" + 
			"Rush\n" + 
			"Porter\n" + 
			"LaPorte\n" + 
			"Starke\n" + 
			"Kosciusko\n" + 
			"Elkhart\n" + 
			"St. Joseph\n" + 
			"LaGrange\n" + 
			"Huntington\n" + 
			"Wells\n" + 
			"Cass\n" + 
			"Wabash\n" + 
			"Dearborn\n" + 
			"Ripley\n" + 
			"Switzerland\n" + 
			"Bartholomew\n" + 
			"Jennings\n" + 
			"Jay\n" + 
			"Blackford\n" + 
			"Dubois\n" + 
			"Warrick\n" + 
			"Posey\n" + 
			"Vanderburgh\n" + 
			"Vigo\n" + 
			"Parke\n" + 
			"Vermillion\n" + 
			"Tippecanoe\n" + 
			"Fountain\n" + 
			"Lapeer\n" + 
			"Macomb\n" + 
			"Oakland\n" + 
			"Washtenaw\n" + 
			"Sanilac\n" + 
			"Shiawassee\n" + 
			"Saginaw\n" + 
			"Tuscola\n" + 
			"Arenac\n" + 
			"Gladwin\n" + 
			"Gratiot\n" + 
			"Clare\n" + 
			"Midland\n" + 
			"Oscoda\n" + 
			"Roscommon\n" + 
			"Ogemaw\n" + 
			"Alcona\n" + 
			"Iosco\n" + 
			"Ionia\n" + 
			"Montcalm\n" + 
			"Eaton\n" + 
			"Ingham\n" + 
			"Isabella\n" + 
			"Barry\n" + 
			"Kalamazoo\n" + 
			"Allegan\n" + 
			"Branch\n" + 
			"Lenawee\n" + 
			"Hillsdale\n" + 
			"Muskegon\n" + 
			"Mecosta\n" + 
			"Newaygo\n" + 
			"Oceana\n" + 
			"Wexford\n" + 
			"Antrim\n" + 
			"Manistee\n" + 
			"Benzie\n" + 
			"Leelanau\n" + 
			"Missaukee\n" + 
			"Kalkaska\n" + 
			"Grand Traverse\n" + 
			"Emmet\n" + 
			"Cheboygan\n" + 
			"Alpena\n" + 
			"Montmorency\n" + 
			"Chippewa\n" + 
			"Charlevoix\n" + 
			"Mackinac\n" + 
			"Presque Isle\n" + 
			"Dickinson\n" + 
			"Keweenaw\n" + 
			"Alger\n" + 
			"Delta\n" + 
			"Marquette\n" + 
			"Menominee\n" + 
			"Schoolcraft\n" + 
			"Luce\n" + 
			"Iron\n" + 
			"Houghton\n" + 
			"Baraga\n" + 
			"Ontonagon\n" + 
			"Gogebic\n" + 
			"Story\n" + 
			"Audubon\n" + 
			"Guthrie\n" + 
			"Mahaska\n" + 
			"Wright\n" + 
			"Ringgold\n" + 
			"Keokuk\n" + 
			"Poweshiek\n" + 
			"Tama\n" + 
			"Cerro Gordo\n" + 
			"Winnebago\n" + 
			"Kossuth\n" + 
			"Palo Alto\n" + 
			"Humboldt\n" + 
			"Sac\n" + 
			"Black Hawk\n" + 
			"Bremer\n" + 
			"Sioux\n" + 
			"Woodbury\n" + 
			"Ida\n" + 
			"O'Brien\n" + 
			"Monona\n" + 
			"Pottawattamie\n" + 
			"Mills\n" + 
			"Fremont\n" + 
			"Dubuque\n" + 
			"Winneshiek\n" + 
			"Allamakee\n" + 
			"Linn\n" + 
			"Iowa\n" + 
			"Cedar\n" + 
			"Wapello\n" + 
			"Davis\n" + 
			"Appanoose\n" + 
			"Des Moines\n" + 
			"Muscatine\n" + 
			"Sheboygan\n" + 
			"Ozaukee\n" + 
			"Waukesha\n" + 
			"Fond du Lac\n" + 
			"Calumet\n" + 
			"Manitowoc\n" + 
			"Kenosha\n" + 
			"Racine\n" + 
			"Milwaukee\n" + 
			"Walworth\n" + 
			"Rock\n" + 
			"Dane\n" + 
			"Sauk\n" + 
			"Green Lake\n" + 
			"Juneau\n" + 
			"St. Croix\n" + 
			"Oconto\n" + 
			"Marinette\n" + 
			"Outagamie\n" + 
			"Shawano\n" + 
			"Kewaunee\n" + 
			"Door\n" + 
			"Marathon\n" + 
			"Langlade\n" + 
			"Price\n" + 
			"Vilas\n" + 
			"Rusk\n" + 
			"La Crosse\n" + 
			"Buffalo\n" + 
			"Trempealeau\n" + 
			"Vernon\n" + 
			"Eau Claire\n" + 
			"Pepin\n" + 
			"Dunn\n" + 
			"Barron\n" + 
			"Washburn\n" + 
			"Bayfield\n" + 
			"Sawyer\n" + 
			"Burnett\n" + 
			"Waupaca\n" + 
			"Waushara\n" + 
			"Anoka\n" + 
			"Isanti\n" + 
			"Kanabec\n" + 
			"Goodhue\n" + 
			"Chisago\n" + 
			"Rice\n" + 
			"Dakota\n" + 
			"Pine\n" + 
			"Wabasha\n" + 
			"Steele\n" + 
			"Ramsey\n" + 
			"Hennepin\n" + 
			"Sibley\n" + 
			"Sherburne\n" + 
			"Renville\n" + 
			"McLeod\n" + 
			"Carver\n" + 
			"Meeker\n" + 
			"Stearns\n" + 
			"Mille Lacs\n" + 
			"St. Louis\n" + 
			"Carlton\n" + 
			"Itasca\n" + 
			"Aitkin\n" + 
			"Koochiching\n" + 
			"Olmsted\n" + 
			"Mower\n" + 
			"Winona\n" + 
			"Fillmore\n" + 
			"Blue Earth\n" + 
			"Nicollet\n" + 
			"Freeborn\n" + 
			"Faribault\n" + 
			"Le Sueur\n" + 
			"Watonwan\n" + 
			"Waseca\n" + 
			"Cottonwood\n" + 
			"Nobles\n" + 
			"Pipestone\n" + 
			"Redwood\n" + 
			"Kandiyohi\n" + 
			"Stevens\n" + 
			"Swift\n" + 
			"Big Stone\n" + 
			"Lac qui Parle\n" + 
			"Traverse\n" + 
			"Yellow Medicine\n" + 
			"Morrison\n" + 
			"Pope\n" + 
			"Otter Tail\n" + 
			"Crow Wing\n" + 
			"Hubbard\n" + 
			"Wadena\n" + 
			"Becker\n" + 
			"Norman\n" + 
			"Mahnomen\n" + 
			"Wilkin\n" + 
			"Beltrami\n" + 
			"Clearwater\n" + 
			"Lake of the Woods\n" + 
			"Roseau\n" + 
			"Pennington\n" + 
			"Red Lake\n" + 
			"Kittson\n" + 
			"Walsh\n" + 
			"Brookings\n" + 
			"Minnehaha\n" + 
			"McCook\n" + 
			"Moody\n" + 
			"Hutchinson\n" + 
			"Yankton\n" + 
			"Kingsbury\n" + 
			"Bon Homme\n" + 
			"Codington\n" + 
			"Deuel\n" + 
			"Day\n" + 
			"Hamlin\n" + 
			"Roberts\n" + 
			"Davison\n" + 
			"Hanson\n" + 
			"Jerauld\n" + 
			"Sanborn\n" + 
			"Gregory\n" + 
			"Beadle\n" + 
			"Miner\n" + 
			"Brule\n" + 
			"Charles Mix\n" + 
			"Aurora\n" + 
			"Hand\n" + 
			"Lyman\n" + 
			"Spink\n" + 
			"Edmunds\n" + 
			"Faulk\n" + 
			"McPherson\n" + 
			"Hughes\n" + 
			"Sully\n" + 
			"Tripp\n" + 
			"Stanley\n" + 
			"Bennett\n" + 
			"Haakon\n" + 
			"Mellette\n" + 
			"Perkins\n" + 
			"Corson\n" + 
			"Ziebach\n" + 
			"Dewey\n" + 
			"Harding\n" + 
			"Oglala Lakota\n" + 
			"Butte\n" + 
			"Fall River\n" + 
			"Custer\n" + 
			"Traill\n" + 
			"Sargent\n" + 
			"Ransom\n" + 
			"Barnes\n" + 
			"LaMoure\n" + 
			"Griggs\n" + 
			"Grand Forks\n" + 
			"Pembina\n" + 
			"Cavalier\n" + 
			"Rolette\n" + 
			"Towner\n" + 
			"Bottineau\n" + 
			"Benson\n" + 
			"Eddy\n" + 
			"Stutsman\n" + 
			"Foster\n" + 
			"Kidder\n" + 
			"Sheridan\n" + 
			"Dickey\n" + 
			"Burleigh\n" + 
			"Morton\n" + 
			"Emmons\n" + 
			"Oliver\n" + 
			"Slope\n" + 
			"Golden Valley\n" + 
			"Bowman\n" + 
			"Billings\n" + 
			"McKenzie\n" + 
			"Hettinger\n" + 
			"Ward\n" + 
			"McHenry\n" + 
			"Divide\n" + 
			"Mountrail\n" + 
			"Stillwater\n" + 
			"Yellowstone\n" + 
			"Rosebud\n" + 
			"Treasure\n" + 
			"Sweet Grass\n" + 
			"Musselshell\n" + 
			"Big Horn\n" + 
			"Park\n" + 
			"Fergus\n" + 
			"Wheatland\n" + 
			"Meagher\n" + 
			"Garfield\n" + 
			"Powder River\n" + 
			"Petroleum\n" + 
			"Roosevelt\n" + 
			"McCone\n" + 
			"Daniels\n" + 
			"Valley\n" + 
			"Phillips\n" + 
			"Fallon\n" + 
			"Prairie\n" + 
			"Wibaux\n" + 
			"Cascade\n" + 
			"Lewis and Clark\n" + 
			"Glacier\n" + 
			"Pondera\n" + 
			"Judith Basin\n" + 
			"Teton\n" + 
			"Chouteau\n" + 
			"Toole\n" + 
			"Hill\n" + 
			"Blaine\n" + 
			"Broadwater\n" + 
			"Silver Bow\n" + 
			"Deer Lodge\n" + 
			"Beaverhead\n" + 
			"Missoula\n" + 
			"Ravalli\n" + 
			"Sanders\n" + 
			"Granite\n" + 
			"Flathead\n" + 
			"DuPage\n" + 
			"Kane\n" + 
			"Ogle\n" + 
			"Will\n" + 
			"LaSalle\n" + 
			"Kendall\n" + 
			"Kankakee\n" + 
			"Iroquois\n" + 
			"Ford\n" + 
			"Vermilion\n" + 
			"Jo Daviess\n" + 
			"Stephenson\n" + 
			"Whiteside\n" + 
			"Rock Island\n" + 
			"Bureau\n" + 
			"McDonough\n" + 
			"Peoria\n" + 
			"De Witt\n" + 
			"Piatt\n" + 
			"Coles\n" + 
			"Moultrie\n" + 
			"Edgar\n" + 
			"Macoupin\n" + 
			"Jersey\n" + 
			"Bond\n" + 
			"Edwards\n" + 
			"Sangamon\n" + 
			"Menard\n" + 
			"Massac\n" + 
			"Saline\n" + 
			"St. Francois\n" + 
			"Gasconade\n" + 
			"St. Charles\n" + 
			"Audrain\n" + 
			"Callaway\n" + 
			"Ralls\n" + 
			"Reynolds\n" + 
			"Ste. Genevieve\n" + 
			"Bollinger\n" + 
			"Cape Girardeau\n" + 
			"Stoddard\n" + 
			"Mississippi\n" + 
			"Dunklin\n" + 
			"Pemiscot\n" + 
			"New Madrid\n" + 
			"Ray\n" + 
			"Platte\n" + 
			"Gentry\n" + 
			"Andrew\n" + 
			"Nodaway\n" + 
			"Holt\n" + 
			"Atchison\n" + 
			"Chariton\n" + 
			"Bates\n" + 
			"Barton\n" + 
			"McDonald\n" + 
			"Osage\n" + 
			"Maries\n" + 
			"Moniteau\n" + 
			"Cole\n" + 
			"Cooper\n" + 
			"Pettis\n" + 
			"Phelps\n" + 
			"Shannon\n" + 
			"Dent\n" + 
			"Texas\n" + 
			"Laclede\n" + 
			"Howell\n" + 
			"Oregon\n" + 
			"Ozark\n" + 
			"Taney\n" + 
			"Hickory\n" + 
			"Leavenworth\n" + 
			"Doniphan\n" + 
			"Wyandotte\n" + 
			"Wabaunsee\n" + 
			"Shawnee\n" + 
			"Nemaha\n" + 
			"Pottawatomie\n" + 
			"Geary\n" + 
			"Riley\n" + 
			"Neosho\n" + 
			"Woodson\n" + 
			"Coffey\n" + 
			"Chase\n" + 
			"Cloud\n" + 
			"Republic\n" + 
			"Jewell\n" + 
			"Sedgwick\n" + 
			"Harper\n" + 
			"Cowley\n" + 
			"Harvey\n" + 
			"Pratt\n" + 
			"Comanche\n" + 
			"Kingman\n" + 
			"Kiowa\n" + 
			"Barber\n" + 
			"Labette\n" + 
			"Osborne\n" + 
			"Ellsworth\n" + 
			"Reno\n" + 
			"Ness\n" + 
			"Pawnee\n" + 
			"Ellis\n" + 
			"Trego\n" + 
			"Rooks\n" + 
			"Rawlins\n" + 
			"Cheyenne\n" + 
			"Sherman\n" + 
			"Gove\n" + 
			"Wallace\n" + 
			"Gray\n" + 
			"Kearny\n" + 
			"Lane\n" + 
			"Finney\n" + 
			"Hodgeman\n" + 
			"Stanton\n" + 
			"Seward\n" + 
			"Wichita\n" + 
			"Haskell\n" + 
			"Greeley\n" + 
			"Saunders\n" + 
			"Cuming\n" + 
			"Sarpy\n" + 
			"Burt\n" + 
			"Thurston\n" + 
			"Gage\n" + 
			"Thayer\n" + 
			"Otoe\n" + 
			"Richardson\n" + 
			"Nance\n" + 
			"Merrick\n" + 
			"Colfax\n" + 
			"Antelope\n" + 
			"Dixon\n" + 
			"Keya Paha\n" + 
			"Loup\n" + 
			"Furnas\n" + 
			"Kearney\n" + 
			"Gosper\n" + 
			"Nuckolls\n" + 
			"Red Willow\n" + 
			"Dundy\n" + 
			"Hitchcock\n" + 
			"Frontier\n" + 
			"Hayes\n" + 
			"Arthur\n" + 
			"Morrill\n" + 
			"Keith\n" + 
			"Kimball\n" + 
			"Cherry\n" + 
			"Garden\n" + 
			"Hooker\n" + 
			"Box Butte\n" + 
			"Dawes\n" + 
			"Scotts Bluff\n" + 
			"Banner\n" + 
			"St. Bernard\n" + 
			"Plaquemines\n" + 
			"St. John the Baptist\n" + 
			"St. James\n" + 
			"Lafourche\n" + 
			"Assumption\n" + 
			"St. Mary\n" + 
			"Terrebonne\n" + 
			"Ascension\n" + 
			"Tangipahoa\n" + 
			"St. Tammany\n" + 
			"St. Helena\n" + 
			"St. Landry\n" + 
			"Iberia\n" + 
			"Evangeline\n" + 
			"Acadia\n" + 
			"St. Martin\n" + 
			"Calcasieu\n" + 
			"Beauregard\n" + 
			"West Baton Rouge\n" + 
			"West Feliciana\n" + 
			"East Baton Rouge\n" + 
			"Pointe Coupee\n" + 
			"Iberville\n" + 
			"East Feliciana\n" + 
			"Bienville\n" + 
			"Caddo\n" + 
			"Bossier\n" + 
			"Red River\n" + 
			"De Soto\n" + 
			"Natchitoches\n" + 
			"Sabine\n" + 
			"Ouachita\n" + 
			"Morehouse\n" + 
			"West Carroll\n" + 
			"East Carroll\n" + 
			"Rapides\n" + 
			"Concordia\n" + 
			"Avoyelles\n" + 
			"Catahoula\n" + 
			"Tensas\n" + 
			"Winn\n" + 
			"Desha\n" + 
			"Ashley\n" + 
			"Chicot\n" + 
			"Drew\n" + 
			"Nevada\n" + 
			"Hempstead\n" + 
			"Little River\n" + 
			"Garland\n" + 
			"Hot Spring\n" + 
			"Arkansas\n" + 
			"Woodruff\n" + 
			"Lonoke\n" + 
			"Conway\n" + 
			"Faulkner\n" + 
			"Independence\n" + 
			"St. Francis\n" + 
			"Cross\n" + 
			"Poinsett\n" + 
			"Craighead\n" + 
			"Sharp\n" + 
			"Izard\n" + 
			"Baxter\n" + 
			"Searcy\n" + 
			"Yell\n" + 
			"Sebastian\n" + 
			"Oklahoma\n" + 
			"McClain\n" + 
			"Canadian\n" + 
			"Kingfisher\n" + 
			"Washita\n" + 
			"Garvin\n" + 
			"Love\n" + 
			"Tillman\n" + 
			"Cotton\n" + 
			"Harmon\n" + 
			"Greer\n" + 
			"Beckham\n" + 
			"Roger Mills\n" + 
			"Alfalfa\n" + 
			"Woods\n" + 
			"Major\n" + 
			"Woodward\n" + 
			"Cimarron\n" + 
			"Tulsa\n" + 
			"Creek\n" + 
			"Wagoner\n" + 
			"Rogers\n" + 
			"Payne\n" + 
			"Nowata\n" + 
			"Okmulgee\n" + 
			"Mayes\n" + 
			"Muskogee\n" + 
			"Pittsburg\n" + 
			"Sequoyah\n" + 
			"Pushmataha\n" + 
			"Atoka\n" + 
			"Coal\n" + 
			"Latimer\n" + 
			"Le Flore\n" + 
			"Kay\n" + 
			"McCurtain\n" + 
			"Okfuskee\n" + 
			"Collin\n" + 
			"Denton\n" + 
			"Rockwall\n" + 
			"Tarrant\n" + 
			"Navarro\n" + 
			"Van Zandt\n" + 
			"Kaufman\n" + 
			"Hunt\n" + 
			"Rains\n" + 
			"Camp\n" + 
			"Titus\n" + 
			"Bowie\n" + 
			"Gregg\n" + 
			"Nacogdoches\n" + 
			"Freestone\n" + 
			"Trinity\n" + 
			"Angelina\n" + 
			"San Augustine\n" + 
			"Parker\n" + 
			"Somervell\n" + 
			"Hood\n" + 
			"Palo Pinto\n" + 
			"Montague\n" + 
			"Cooke\n" + 
			"Archer\n" + 
			"Wilbarger\n" + 
			"Young\n" + 
			"Baylor\n" + 
			"Erath\n" + 
			"Jack\n" + 
			"Shackelford\n" + 
			"Eastland\n" + 
			"Callahan\n" + 
			"Throckmorton\n" + 
			"Milam\n" + 
			"Falls\n" + 
			"Coryell\n" + 
			"McLennan\n" + 
			"Lampasas\n" + 
			"Bosque\n" + 
			"Runnels\n" + 
			"San Saba\n" + 
			"McCulloch\n" + 
			"Coleman\n" + 
			"Llano\n" + 
			"Concho\n" + 
			"Kimble\n" + 
			"Tom Green\n" + 
			"Irion\n" + 
			"Reagan\n" + 
			"Coke\n" + 
			"Schleicher\n" + 
			"Sutton\n" + 
			"Sterling\n" + 
			"Fort Bend\n" + 
			"San Jacinto\n" + 
			"Grimes\n" + 
			"Colorado\n" + 
			"Matagorda\n" + 
			"Austin\n" + 
			"Wharton\n" + 
			"Brazoria\n" + 
			"Waller\n" + 
			"Galveston\n" + 
			"Brazos\n" + 
			"Burleson\n" + 
			"Victoria\n" + 
			"Refugio\n" + 
			"DeWitt\n" + 
			"Goliad\n" + 
			"Lavaca\n" + 
			"La Salle\n" + 
			"Bexar\n" + 
			"Bandera\n" + 
			"Frio\n" + 
			"McMullen\n" + 
			"Atascosa\n" + 
			"Kerr\n" + 
			"Live Oak\n" + 
			"Webb\n" + 
			"Gillespie\n" + 
			"Zapata\n" + 
			"Comal\n" + 
			"Bee\n" + 
			"Guadalupe\n" + 
			"Karnes\n" + 
			"Gonzales\n" + 
			"Nueces\n" + 
			"Jim Wells\n" + 
			"San Patricio\n" + 
			"Kenedy\n" + 
			"Aransas\n" + 
			"Jim Hogg\n" + 
			"Kleberg\n" + 
			"Hidalgo\n" + 
			"Starr\n" + 
			"Willacy\n" + 
			"Bastrop\n" + 
			"Burnet\n" + 
			"Blanco\n" + 
			"Hays\n" + 
			"Travis\n" + 
			"Uvalde\n" + 
			"Dimmit\n" + 
			"Zavala\n" + 
			"Kinney\n" + 
			"Val Verde\n" + 
			"Maverick\n" + 
			"Real\n" + 
			"Lipscomb\n" + 
			"Parmer\n" + 
			"Hemphill\n" + 
			"Randall\n" + 
			"Hartley\n" + 
			"Dallam\n" + 
			"Deaf Smith\n" + 
			"Castro\n" + 
			"Lamb\n" + 
			"Ochiltree\n" + 
			"Carson\n" + 
			"Hansford\n" + 
			"Swisher\n" + 
			"Collingsworth\n" + 
			"Childress\n" + 
			"Dickens\n" + 
			"Donley\n" + 
			"Foard\n" + 
			"Motley\n" + 
			"King\n" + 
			"Cottle\n" + 
			"Briscoe\n" + 
			"Hockley\n" + 
			"Cochran\n" + 
			"Terry\n" + 
			"Crosby\n" + 
			"Yoakum\n" + 
			"Bailey\n" + 
			"Lubbock\n" + 
			"Garza\n" + 
			"Gaines\n" + 
			"Borden\n" + 
			"Lynn\n" + 
			"Stonewall\n" + 
			"Nolan\n" + 
			"Scurry\n" + 
			"Fisher\n" + 
			"Andrews\n" + 
			"Reeves\n" + 
			"Pecos\n" + 
			"Crane\n" + 
			"Glasscock\n" + 
			"Ector\n" + 
			"Winkler\n" + 
			"Upton\n" + 
			"Loving\n" + 
			"El Paso\n" + 
			"Brewster\n" + 
			"Hudspeth\n" + 
			"Presidio\n" + 
			"Culberson\n" + 
			"Arapahoe\n" + 
			"Broomfield\n" + 
			"Boulder\n" + 
			"Denver\n" + 
			"Gilpin\n" + 
			"Eagle\n" + 
			"Routt\n" + 
			"Clear Creek\n" + 
			"Grand\n" + 
			"Larimer\n" + 
			"Weld\n" + 
			"Yuma\n" + 
			"Kit Carson\n" + 
			"Teller\n" + 
			"Pueblo\n" + 
			"Las Animas\n" + 
			"Baca\n" + 
			"Otero\n" + 
			"Crowley\n" + 
			"Bent\n" + 
			"Huerfano\n" + 
			"Prowers\n" + 
			"Alamosa\n" + 
			"Conejos\n" + 
			"Archuleta\n" + 
			"La Plata\n" + 
			"Costilla\n" + 
			"Saguache\n" + 
			"Rio Grande\n" + 
			"Chaffee\n" + 
			"Gunnison\n" + 
			"Hinsdale\n" + 
			"Dolores\n" + 
			"Montezuma\n" + 
			"San Miguel\n" + 
			"Montrose\n" + 
			"Ouray\n" + 
			"San Juan\n" + 
			"Mesa\n" + 
			"Moffat\n" + 
			"Pitkin\n" + 
			"Rio Blanco\n" + 
			"Laramie\n" + 
			"Goshen\n" + 
			"Niobrara\n" + 
			"Converse\n" + 
			"Sweetwater\n" + 
			"Washakie\n" + 
			"Hot Springs\n" + 
			"Natrona\n" + 
			"Weston\n" + 
			"Crook\n" + 
			"Sublette\n" + 
			"Uinta\n" + 
			"Bannock\n" + 
			"Bingham\n" + 
			"Power\n" + 
			"Caribou\n" + 
			"Bear Lake\n" + 
			"Lemhi\n" + 
			"Bonneville\n" + 
			"Twin Falls\n" + 
			"Cassia\n" + 
			"Gooding\n" + 
			"Camas\n" + 
			"Jerome\n" + 
			"Minidoka\n" + 
			"Nez Perce\n" + 
			"Idaho\n" + 
			"Latah\n" + 
			"Boise\n" + 
			"Owyhee\n" + 
			"Canyon\n" + 
			"Ada\n" + 
			"Gem\n" + 
			"Payette\n" + 
			"Kootenai\n" + 
			"Shoshone\n" + 
			"Bonner\n" + 
			"Boundary\n" + 
			"Benewah\n" + 
			"Duchesne\n" + 
			"Utah\n" + 
			"Salt Lake\n" + 
			"Tooele\n" + 
			"Daggett\n" + 
			"Uintah\n" + 
			"Rich\n" + 
			"Wasatch\n" + 
			"Weber\n" + 
			"Box Elder\n" + 
			"Cache\n" + 
			"Emery\n" + 
			"Sanpete\n" + 
			"Millard\n" + 
			"Juab\n" + 
			"Piute\n" + 
			"Maricopa\n" + 
			"Pinal\n" + 
			"Gila\n" + 
			"Pima\n" + 
			"Yavapai\n" + 
			"La Paz\n" + 
			"Mohave\n" + 
			"Greenlee\n" + 
			"Cochise\n" + 
			"Santa Cruz\n" + 
			"Navajo\n" + 
			"Apache\n" + 
			"Coconino\n" + 
			"Sandoval\n" + 
			"Valencia\n" + 
			"Cibola\n" + 
			"Socorro\n" + 
			"Bernalillo\n" + 
			"Santa Fe\n" + 
			"Rio Arriba\n" + 
			"Torrance\n" + 
			"McKinley\n" + 
			"Taos\n" + 
			"Los Alamos\n" + 
			"Mora\n" + 
			"Catron\n" + 
			"Sierra\n" + 
			"DoÌ±a Ana\n" + 
			"Luna\n" + 
			"Curry\n" + 
			"Lea\n" + 
			"De Baca\n" + 
			"Quay\n" + 
			"Chaves\n" + 
			"Nye\n" + 
			"Esmeralda\n" + 
			"White Pine\n" + 
			"Lander\n" + 
			"Eureka\n" + 
			"Washoe\n" + 
			"Churchill\n" + 
			"Pershing\n" + 
			"Storey\n" + 
			"Carson City\n" + 
			"Elko\n" + 
			"Los Angeles\n" + 
			"Ventura\n" + 
			"San Bernardino\n" + 
			"Riverside\n" + 
			"San Diego\n" + 
			"Imperial\n" + 
			"Inyo\n" + 
			"Santa Barbara\n" + 
			"Tulare\n" + 
			"Kern\n" + 
			"Fresno\n" + 
			"San Luis Obispo\n" + 
			"Monterey\n" + 
			"Mono\n" + 
			"Madera\n" + 
			"Merced\n" + 
			"Mariposa\n" + 
			"San Mateo\n" + 
			"Santa Clara\n" + 
			"San Francisco\n" + 
			"Alameda\n" + 
			"Napa\n" + 
			"Contra Costa\n" + 
			"Solano\n" + 
			"Marin\n" + 
			"Sonoma\n" + 
			"San Benito\n" + 
			"San Joaquin\n" + 
			"Calaveras\n" + 
			"Tuolumne\n" + 
			"Stanislaus\n" + 
			"Mendocino\n" + 
			"Del Norte\n" + 
			"Siskiyou\n" + 
			"Amador\n" + 
			"Placer\n" + 
			"Yolo\n" + 
			"Sacramento\n" + 
			"El Dorado\n" + 
			"Alpine\n" + 
			"Sutter\n" + 
			"Yuba\n" + 
			"Colusa\n" + 
			"Plumas\n" + 
			"Glenn\n" + 
			"Shasta\n" + 
			"Modoc\n" + 
			"Lassen\n" + 
			"Tehama\n" + 
			"Honolulu\n" + 
			"Kauai\n" + 
			"Hawaii\n" + 
			"Maui\n" + 
			"Kalawao\n" + 
			"Wasco\n" + 
			"Clackamas\n" + 
			"Hood River\n" + 
			"Multnomah\n" + 
			"Yamhill\n" + 
			"Clatsop\n" + 
			"Tillamook\n" + 
			"Josephine\n" + 
			"Klamath\n" + 
			"Deschutes\n" + 
			"Harney\n" + 
			"Umatilla\n" + 
			"Gilliam\n" + 
			"Wallowa\n" + 
			"Malheur\n" + 
			"Snohomish\n" + 
			"Kittitas\n" + 
			"Kitsap\n" + 
			"Whatcom\n" + 
			"Skagit\n" + 
			"Island\n" + 
			"Clallam\n" + 
			"Grays Harbor\n" + 
			"Pacific\n" + 
			"Cowlitz\n" + 
			"Klickitat\n" + 
			"Skamania\n" + 
			"Wahkiakum\n" + 
			"Chelan\n" + 
			"Okanogan\n" + 
			"Yakima\n" + 
			"Spokane\n" + 
			"Whitman\n" + 
			"Ferry\n" + 
			"Pend Oreille\n" + 
			"Walla Walla\n" + 
			"Asotin\n" + 
			"Anchorage\n" + 
			"North Slope\n" + 
			"Aleutians West\n" + 
			"Lake and Peninsula\n" + 
			"Kodiak Island\n" + 
			"Bethel\n" + 
			"Aleutians East\n" + 
			"Wade Hampton\n" + 
			"Dillingham\n" + 
			"Kenai Peninsula\n" + 
			"Yukon-Koyukuk\n" + 
			"Valdez-Cordova\n" + 
			"Bristol Bay\n" + 
			"Matanuska-Susitna\n" + 
			"Nome\n" + 
			"Yakutat\n" + 
			"Fairbanks North Star\n" + 
			"Denali\n" + 
			"Southeast Fairbanks\n" + 
			"Northwest Arctic\n" + 
			"Hoonah-Angoon\n" + 
			"Haines\n" + 
			"Sitka\n" + 
			"Skagway\n" + 
			"Ketchikan Gateway\n" + 
			"Wrangell\n" + 
			"Prince of Wales-Hyder\n";
	
	String[] unrCn = unrepeatedCounties.split("\n");
	return unrCn;
	
	}
	
	public static String[] getAllCounties() {
		String allCt = "Autauga\n" + 
				"Baldwin\n" + 
				"Barbour\n" + 
				"Bibb\n" + 
				"Blount\n" + 
				"Bullock\n" + 
				"Butler\n" + 
				"Calhoun\n" + 
				"Chambers\n" + 
				"Cherokee\n" + 
				"Chilton\n" + 
				"Choctaw\n" + 
				"Clarke\n" + 
				"Clay\n" + 
				"Cleburne\n" + 
				"Coffee\n" + 
				"Colbert\n" + 
				"Conecuh\n" + 
				"Coosa\n" + 
				"Covington\n" + 
				"Crenshaw\n" + 
				"Cullman\n" + 
				"Dale\n" + 
				"Dallas\n" + 
				"DeKalb\n" + 
				"Elmore\n" + 
				"Escambia\n" + 
				"Etowah\n" + 
				"Fayette\n" + 
				"Franklin\n" + 
				"Geneva\n" + 
				"Greene\n" + 
				"Hale\n" + 
				"Henry\n" + 
				"Houston\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Lamar\n" + 
				"Lauderdale\n" + 
				"Lawrence\n" + 
				"Lee\n" + 
				"Limestone\n" + 
				"Lowndes\n" + 
				"Macon\n" + 
				"Madison\n" + 
				"Marengo\n" + 
				"Marion\n" + 
				"Marshall\n" + 
				"Mobile\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Morgan\n" + 
				"Perry\n" + 
				"Pickens\n" + 
				"Pike\n" + 
				"Randolph\n" + 
				"Russell\n" + 
				"St. Clair\n" + 
				"Shelby\n" + 
				"Sumter\n" + 
				"Talladega\n" + 
				"Tallapoosa\n" + 
				"Tuscaloosa\n" + 
				"Walker\n" + 
				"Washington\n" + 
				"Wilcox\n" + 
				"Winston\n" + 
				"Apache\n" + 
				"Cochise\n" + 
				"Coconino\n" + 
				"Gila\n" + 
				"Graham\n" + 
				"Greenlee\n" + 
				"La Paz\n" + 
				"Maricopa\n" + 
				"Mohave\n" + 
				"Navajo\n" + 
				"Pima\n" + 
				"Pinal\n" + 
				"Santa Cruz\n" + 
				"Yavapai\n" + 
				"Yuma\n" + 
				"Arkansas\n" + 
				"Ashley\n" + 
				"Baxter\n" + 
				"Benton\n" + 
				"Boone\n" + 
				"Bradley\n" + 
				"Calhoun\n" + 
				"Carroll\n" + 
				"Chicot\n" + 
				"Clark\n" + 
				"Clay\n" + 
				"Cleburne\n" + 
				"Cleveland\n" + 
				"Columbia\n" + 
				"Conway\n" + 
				"Craighead\n" + 
				"Crawford\n" + 
				"Crittenden\n" + 
				"Cross\n" + 
				"Dallas\n" + 
				"Desha\n" + 
				"Drew\n" + 
				"Faulkner\n" + 
				"Franklin\n" + 
				"Fulton\n" + 
				"Garland\n" + 
				"Grant\n" + 
				"Greene\n" + 
				"Hempstead\n" + 
				"Hot Spring\n" + 
				"Howard\n" + 
				"Independence\n" + 
				"Izard\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Johnson\n" + 
				"Lafayette\n" + 
				"Lawrence\n" + 
				"Lee\n" + 
				"Lincoln\n" + 
				"Little River\n" + 
				"Logan\n" + 
				"Lonoke\n" + 
				"Madison\n" + 
				"Marion\n" + 
				"Miller\n" + 
				"Mississippi\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Nevada\n" + 
				"Newton\n" + 
				"Ouachita\n" + 
				"Perry\n" + 
				"Phillips\n" + 
				"Pike\n" + 
				"Poinsett\n" + 
				"Polk\n" + 
				"Pope\n" + 
				"Prairie\n" + 
				"Pulaski\n" + 
				"Randolph\n" + 
				"St. Francis\n" + 
				"Saline\n" + 
				"Scott\n" + 
				"Searcy\n" + 
				"Sebastian\n" + 
				"Sevier\n" + 
				"Sharp\n" + 
				"Stone\n" + 
				"Union\n" + 
				"Van Buren\n" + 
				"Washington\n" + 
				"White\n" + 
				"Woodruff\n" + 
				"Yell\n" + 
				"Alameda\n" + 
				"Alpine\n" + 
				"Amador\n" + 
				"Butte\n" + 
				"Calaveras\n" + 
				"Colusa\n" + 
				"Contra Costa\n" + 
				"Del Norte\n" + 
				"El Dorado\n" + 
				"Fresno\n" + 
				"Glenn\n" + 
				"Humboldt\n" + 
				"Imperial\n" + 
				"Inyo\n" + 
				"Kern\n" + 
				"Kings\n" + 
				"Lake\n" + 
				"Lassen\n" + 
				"Los Angeles\n" + 
				"Madera\n" + 
				"Marin\n" + 
				"Mariposa\n" + 
				"Mendocino\n" + 
				"Merced\n" + 
				"Modoc\n" + 
				"Mono\n" + 
				"Monterey\n" + 
				"Napa\n" + 
				"Nevada\n" + 
				"Orange\n" + 
				"Placer\n" + 
				"Plumas\n" + 
				"Riverside\n" + 
				"Sacramento\n" + 
				"San Benito\n" + 
				"San Bernardino\n" + 
				"San Diego\n" + 
				"San Francisco\n" + 
				"San Joaquin\n" + 
				"San Luis Obispo\n" + 
				"San Mateo\n" + 
				"Santa Barbara\n" + 
				"Santa Clara\n" + 
				"Santa Cruz\n" + 
				"Shasta\n" + 
				"Sierra\n" + 
				"Siskiyou\n" + 
				"Solano\n" + 
				"Sonoma\n" + 
				"Stanislaus\n" + 
				"Sutter\n" + 
				"Tehama\n" + 
				"Trinity\n" + 
				"Tulare\n" + 
				"Tuolumne\n" + 
				"Ventura\n" + 
				"Yolo\n" + 
				"Yuba\n" + 
				"Adams\n" + 
				"Alamosa\n" + 
				"Arapahoe\n" + 
				"Archuleta\n" + 
				"Baca\n" + 
				"Bent\n" + 
				"Boulder\n" + 
				"Broomfield\n" + 
				"Chaffee\n" + 
				"Cheyenne\n" + 
				"Clear Creek\n" + 
				"Conejos\n" + 
				"Costilla\n" + 
				"Crowley\n" + 
				"Custer\n" + 
				"Delta\n" + 
				"Denver\n" + 
				"Dolores\n" + 
				"Douglas\n" + 
				"Eagle\n" + 
				"Elbert\n" + 
				"El Paso\n" + 
				"Fremont\n" + 
				"Garfield\n" + 
				"Gilpin\n" + 
				"Grand\n" + 
				"Gunnison\n" + 
				"Hinsdale\n" + 
				"Huerfano\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Kiowa\n" + 
				"Kit Carson\n" + 
				"Lake\n" + 
				"La Plata\n" + 
				"Larimer\n" + 
				"Las Animas\n" + 
				"Lincoln\n" + 
				"Logan\n" + 
				"Mesa\n" + 
				"Mineral\n" + 
				"Moffat\n" + 
				"Montezuma\n" + 
				"Montrose\n" + 
				"Morgan\n" + 
				"Otero\n" + 
				"Ouray\n" + 
				"Park\n" + 
				"Phillips\n" + 
				"Pitkin\n" + 
				"Prowers\n" + 
				"Pueblo\n" + 
				"Rio Blanco\n" + 
				"Rio Grande\n" + 
				"Routt\n" + 
				"Saguache\n" + 
				"San Juan\n" + 
				"San Miguel\n" + 
				"Sedgwick\n" + 
				"Summit\n" + 
				"Teller\n" + 
				"Washington\n" + 
				"Weld\n" + 
				"Yuma\n" + 
				"Fairfield\n" + 
				"Hartford\n" + 
				"Litchfield\n" + 
				"Middlesex\n" + 
				"New Haven\n" + 
				"New London\n" + 
				"Tolland\n" + 
				"Windham\n" + 
				"Kent\n" + 
				"New Castle\n" + 
				"Sussex\n" + 
				"District of Columbia\n" + 
				"Alachua\n" + 
				"Baker\n" + 
				"Bay\n" + 
				"Bradford\n" + 
				"Brevard\n" + 
				"Broward\n" + 
				"Calhoun\n" + 
				"Charlotte\n" + 
				"Citrus\n" + 
				"Clay\n" + 
				"Collier\n" + 
				"Columbia\n" + 
				"Desoto\n" + 
				"Dixie\n" + 
				"Duval\n" + 
				"Escambia\n" + 
				"Flagler\n" + 
				"Franklin\n" + 
				"Gadsden\n" + 
				"Gilchrist\n" + 
				"Glades\n" + 
				"Gulf\n" + 
				"Hamilton\n" + 
				"Hardee\n" + 
				"Hendry\n" + 
				"Hernando\n" + 
				"Highlands\n" + 
				"Hillsborough\n" + 
				"Holmes\n" + 
				"Indian River\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Lafayette\n" + 
				"Lake\n" + 
				"Lee\n" + 
				"Leon\n" + 
				"Levy\n" + 
				"Liberty\n" + 
				"Madison\n" + 
				"Manatee\n" + 
				"Marion\n" + 
				"Martin\n" + 
				"Miami-Dade\n" + 
				"Monroe\n" + 
				"Nassau\n" + 
				"Okaloosa\n" + 
				"Okeechobee\n" + 
				"Orange\n" + 
				"Osceola\n" + 
				"Palm Beach\n" + 
				"Pasco\n" + 
				"Pinellas\n" + 
				"Polk\n" + 
				"Putnam\n" + 
				"St. Johns\n" + 
				"St. Lucie\n" + 
				"Santa Rosa\n" + 
				"Sarasota\n" + 
				"Seminole\n" + 
				"Sumter\n" + 
				"Suwannee\n" + 
				"Taylor\n" + 
				"Union\n" + 
				"Volusia\n" + 
				"Wakulla\n" + 
				"Walton\n" + 
				"Washington\n" + 
				"Appling\n" + 
				"Atkinson\n" + 
				"Bacon\n" + 
				"Baker\n" + 
				"Baldwin\n" + 
				"Banks\n" + 
				"Barrow\n" + 
				"Bartow\n" + 
				"Ben Hill\n" + 
				"Berrien\n" + 
				"Bibb\n" + 
				"Bleckley\n" + 
				"Brantley\n" + 
				"Brooks\n" + 
				"Bryan\n" + 
				"Bulloch\n" + 
				"Burke\n" + 
				"Butts\n" + 
				"Calhoun\n" + 
				"Camden\n" + 
				"Candler\n" + 
				"Carroll\n" + 
				"Catoosa\n" + 
				"Charlton\n" + 
				"Chatham\n" + 
				"Chattahoochee\n" + 
				"Chattooga\n" + 
				"Cherokee\n" + 
				"Clarke\n" + 
				"Clay\n" + 
				"Clayton\n" + 
				"Clinch\n" + 
				"Cobb\n" + 
				"Coffee\n" + 
				"Colquitt\n" + 
				"Columbia\n" + 
				"Cook\n" + 
				"Coweta\n" + 
				"Crawford\n" + 
				"Crisp\n" + 
				"Dade\n" + 
				"Dawson\n" + 
				"Decatur\n" + 
				"DeKalb\n" + 
				"Dodge\n" + 
				"Dooly\n" + 
				"Dougherty\n" + 
				"Douglas\n" + 
				"Early\n" + 
				"Echols\n" + 
				"Effingham\n" + 
				"Elbert\n" + 
				"Emanuel\n" + 
				"Evans\n" + 
				"Fannin\n" + 
				"Fayette\n" + 
				"Floyd\n" + 
				"Forsyth\n" + 
				"Franklin\n" + 
				"Fulton\n" + 
				"Gilmer\n" + 
				"Glascock\n" + 
				"Glynn\n" + 
				"Gordon\n" + 
				"Grady\n" + 
				"Greene\n" + 
				"Gwinnett\n" + 
				"Habersham\n" + 
				"Hall\n" + 
				"Hancock\n" + 
				"Haralson\n" + 
				"Harris\n" + 
				"Hart\n" + 
				"Heard\n" + 
				"Henry\n" + 
				"Houston\n" + 
				"Irwin\n" + 
				"Jackson\n" + 
				"Jasper\n" + 
				"Jeff Davis\n" + 
				"Jefferson\n" + 
				"Jenkins\n" + 
				"Johnson\n" + 
				"Jones\n" + 
				"Lamar\n" + 
				"Lanier\n" + 
				"Laurens\n" + 
				"Lee\n" + 
				"Liberty\n" + 
				"Lincoln\n" + 
				"Long\n" + 
				"Lowndes\n" + 
				"Lumpkin\n" + 
				"McDuffie\n" + 
				"McIntosh\n" + 
				"Macon\n" + 
				"Madison\n" + 
				"Marion\n" + 
				"Meriwether\n" + 
				"Miller\n" + 
				"Mitchell\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Morgan\n" + 
				"Murray\n" + 
				"Muscogee\n" + 
				"Newton\n" + 
				"Oconee\n" + 
				"Oglethorpe\n" + 
				"Paulding\n" + 
				"Peach\n" + 
				"Pickens\n" + 
				"Pierce\n" + 
				"Pike\n" + 
				"Polk\n" + 
				"Pulaski\n" + 
				"Putnam\n" + 
				"Quitman\n" + 
				"Rabun\n" + 
				"Randolph\n" + 
				"Richmond\n" + 
				"Rockdale\n" + 
				"Schley\n" + 
				"Screven\n" + 
				"Seminole\n" + 
				"Spalding\n" + 
				"Stephens\n" + 
				"Stewart\n" + 
				"Sumter\n" + 
				"Talbot\n" + 
				"Taliaferro\n" + 
				"Tattnall\n" + 
				"Taylor\n" + 
				"Telfair\n" + 
				"Terrell\n" + 
				"Thomas\n" + 
				"Tift\n" + 
				"Toombs\n" + 
				"Towns\n" + 
				"Treutlen\n" + 
				"Troup\n" + 
				"Turner\n" + 
				"Twiggs\n" + 
				"Union\n" + 
				"Upson\n" + 
				"Walker\n" + 
				"Walton\n" + 
				"Ware\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Webster\n" + 
				"Wheeler\n" + 
				"White\n" + 
				"Whitfield\n" + 
				"Wilcox\n" + 
				"Wilkes\n" + 
				"Wilkinson\n" + 
				"Worth\n" + 
				"Hawaii\n" + 
				"Honolulu\n" + 
				"Kauai\n" + 
				"Ada\n" + 
				"Adams\n" + 
				"Bannock\n" + 
				"Bear Lake\n" + 
				"Benewah\n" + 
				"Bingham\n" + 
				"Blaine\n" + 
				"Boise\n" + 
				"Bonner\n" + 
				"Bonneville\n" + 
				"Boundary\n" + 
				"Butte\n" + 
				"Camas\n" + 
				"Canyon\n" + 
				"Caribou\n" + 
				"Cassia\n" + 
				"Clark\n" + 
				"Clearwater\n" + 
				"Custer\n" + 
				"Elmore\n" + 
				"Franklin\n" + 
				"Fremont\n" + 
				"Gem\n" + 
				"Gooding\n" + 
				"Idaho\n" + 
				"Jefferson\n" + 
				"Jerome\n" + 
				"Kootenai\n" + 
				"Latah\n" + 
				"Lemhi\n" + 
				"Lewis\n" + 
				"Lincoln\n" + 
				"Madison\n" + 
				"Minidoka\n" + 
				"Nez Perce\n" + 
				"Oneida\n" + 
				"Owyhee\n" + 
				"Payette\n" + 
				"Power\n" + 
				"Shoshone\n" + 
				"Teton\n" + 
				"Twin Falls\n" + 
				"Valley\n" + 
				"Washington\n" + 
				"Adams\n" + 
				"Alexander\n" + 
				"Bond\n" + 
				"Boone\n" + 
				"Brown\n" + 
				"Bureau\n" + 
				"Calhoun\n" + 
				"Carroll\n" + 
				"Cass\n" + 
				"Champaign\n" + 
				"Christian\n" + 
				"Clark\n" + 
				"Clay\n" + 
				"Clinton\n" + 
				"Coles\n" + 
				"Cook\n" + 
				"Crawford\n" + 
				"Cumberland\n" + 
				"DeKalb\n" + 
				"De Witt\n" + 
				"Douglas\n" + 
				"DuPage\n" + 
				"Edgar\n" + 
				"Edwards\n" + 
				"Effingham\n" + 
				"Fayette\n" + 
				"Ford\n" + 
				"Franklin\n" + 
				"Fulton\n" + 
				"Gallatin\n" + 
				"Greene\n" + 
				"Grundy\n" + 
				"Hamilton\n" + 
				"Hancock\n" + 
				"Hardin\n" + 
				"Henderson\n" + 
				"Henry\n" + 
				"Iroquois\n" + 
				"Jackson\n" + 
				"Jasper\n" + 
				"Jefferson\n" + 
				"Jersey\n" + 
				"Jo Daviess\n" + 
				"Johnson\n" + 
				"Kane\n" + 
				"Kankakee\n" + 
				"Kendall\n" + 
				"Knox\n" + 
				"Lake\n" + 
				"LaSalle\n" + 
				"Lawrence\n" + 
				"Lee\n" + 
				"Livingston\n" + 
				"Logan\n" + 
				"McDonough\n" + 
				"McHenry\n" + 
				"McLean\n" + 
				"Macon\n" + 
				"Macoupin\n" + 
				"Madison\n" + 
				"Marion\n" + 
				"Marshall\n" + 
				"Mason\n" + 
				"Massac\n" + 
				"Menard\n" + 
				"Mercer\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Morgan\n" + 
				"Moultrie\n" + 
				"Ogle\n" + 
				"Peoria\n" + 
				"Perry\n" + 
				"Piatt\n" + 
				"Pike\n" + 
				"Pope\n" + 
				"Pulaski\n" + 
				"Putnam\n" + 
				"Randolph\n" + 
				"Richland\n" + 
				"Rock Island\n" + 
				"St. Clair\n" + 
				"Saline\n" + 
				"Sangamon\n" + 
				"Schuyler\n" + 
				"Scott\n" + 
				"Shelby\n" + 
				"Stark\n" + 
				"Stephenson\n" + 
				"Tazewell\n" + 
				"Union\n" + 
				"Vermilion\n" + 
				"Wabash\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"White\n" + 
				"Whiteside\n" + 
				"Will\n" + 
				"Williamson\n" + 
				"Winnebago\n" + 
				"Woodford\n" + 
				"Adams\n" + 
				"Allen\n" + 
				"Bartholomew\n" + 
				"Benton\n" + 
				"Blackford\n" + 
				"Boone\n" + 
				"Brown\n" + 
				"Carroll\n" + 
				"Cass\n" + 
				"Clark\n" + 
				"Clay\n" + 
				"Clinton\n" + 
				"Crawford\n" + 
				"Daviess\n" + 
				"Dearborn\n" + 
				"Decatur\n" + 
				"DeKalb\n" + 
				"Delaware\n" + 
				"Dubois\n" + 
				"Elkhart\n" + 
				"Fayette\n" + 
				"Floyd\n" + 
				"Fountain\n" + 
				"Franklin\n" + 
				"Fulton\n" + 
				"Gibson\n" + 
				"Grant\n" + 
				"Greene\n" + 
				"Hamilton\n" + 
				"Hancock\n" + 
				"Harrison\n" + 
				"Hendricks\n" + 
				"Henry\n" + 
				"Howard\n" + 
				"Huntington\n" + 
				"Jackson\n" + 
				"Jasper\n" + 
				"Jay\n" + 
				"Jefferson\n" + 
				"Jennings\n" + 
				"Johnson\n" + 
				"Knox\n" + 
				"Kosciusko\n" + 
				"LaGrange\n" + 
				"Lake\n" + 
				"LaPorte\n" + 
				"Lawrence\n" + 
				"Madison\n" + 
				"Marion\n" + 
				"Marshall\n" + 
				"Martin\n" + 
				"Miami\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Morgan\n" + 
				"Newton\n" + 
				"Noble\n" + 
				"Ohio\n" + 
				"Orange\n" + 
				"Owen\n" + 
				"Parke\n" + 
				"Perry\n" + 
				"Pike\n" + 
				"Porter\n" + 
				"Posey\n" + 
				"Pulaski\n" + 
				"Putnam\n" + 
				"Randolph\n" + 
				"Ripley\n" + 
				"Rush\n" + 
				"St. Joseph\n" + 
				"Scott\n" + 
				"Shelby\n" + 
				"Spencer\n" + 
				"Starke\n" + 
				"Steuben\n" + 
				"Sullivan\n" + 
				"Switzerland\n" + 
				"Tippecanoe\n" + 
				"Tipton\n" + 
				"Union\n" + 
				"Vanderburgh\n" + 
				"Vermillion\n" + 
				"Vigo\n" + 
				"Wabash\n" + 
				"Warren\n" + 
				"Warrick\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Wells\n" + 
				"White\n" + 
				"Whitley\n" + 
				"Adair\n" + 
				"Adams\n" + 
				"Allamakee\n" + 
				"Appanoose\n" + 
				"Audubon\n" + 
				"Benton\n" + 
				"Black Hawk\n" + 
				"Boone\n" + 
				"Bremer\n" + 
				"Buchanan\n" + 
				"Buena Vista\n" + 
				"Butler\n" + 
				"Calhoun\n" + 
				"Carroll\n" + 
				"Cass\n" + 
				"Cedar\n" + 
				"Cerro Gordo\n" + 
				"Cherokee\n" + 
				"Chickasaw\n" + 
				"Clarke\n" + 
				"Clay\n" + 
				"Clayton\n" + 
				"Clinton\n" + 
				"Crawford\n" + 
				"Dallas\n" + 
				"Davis\n" + 
				"Decatur\n" + 
				"Delaware\n" + 
				"Des Moines\n" + 
				"Dickinson\n" + 
				"Dubuque\n" + 
				"Emmet\n" + 
				"Fayette\n" + 
				"Floyd\n" + 
				"Franklin\n" + 
				"Fremont\n" + 
				"Greene\n" + 
				"Grundy\n" + 
				"Guthrie\n" + 
				"Hamilton\n" + 
				"Hancock\n" + 
				"Hardin\n" + 
				"Harrison\n" + 
				"Henry\n" + 
				"Howard\n" + 
				"Humboldt\n" + 
				"Ida\n" + 
				"Iowa\n" + 
				"Jackson\n" + 
				"Jasper\n" + 
				"Jefferson\n" + 
				"Johnson\n" + 
				"Jones\n" + 
				"Keokuk\n" + 
				"Kossuth\n" + 
				"Lee\n" + 
				"Linn\n" + 
				"Louisa\n" + 
				"Lucas\n" + 
				"Lyon\n" + 
				"Madison\n" + 
				"Mahaska\n" + 
				"Marion\n" + 
				"Marshall\n" + 
				"Mills\n" + 
				"Mitchell\n" + 
				"Monona\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Muscatine\n" + 
				"O'Brien\n" + 
				"Osceola\n" + 
				"Page\n" + 
				"Palo Alto\n" + 
				"Plymouth\n" + 
				"Pocahontas\n" + 
				"Polk\n" + 
				"Pottawattamie\n" + 
				"Poweshiek\n" + 
				"Ringgold\n" + 
				"Sac\n" + 
				"Scott\n" + 
				"Shelby\n" + 
				"Sioux\n" + 
				"Story\n" + 
				"Tama\n" + 
				"Taylor\n" + 
				"Union\n" + 
				"Van Buren\n" + 
				"Wapello\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Webster\n" + 
				"Winnebago\n" + 
				"Winneshiek\n" + 
				"Woodbury\n" + 
				"Worth\n" + 
				"Wright\n" + 
				"Allen\n" + 
				"Anderson\n" + 
				"Atchison\n" + 
				"Barber\n" + 
				"Barton\n" + 
				"Bourbon\n" + 
				"Brown\n" + 
				"Butler\n" + 
				"Chase\n" + 
				"Chautauqua\n" + 
				"Cherokee\n" + 
				"Cheyenne\n" + 
				"Clark\n" + 
				"Clay\n" + 
				"Cloud\n" + 
				"Coffey\n" + 
				"Comanche\n" + 
				"Cowley\n" + 
				"Crawford\n" + 
				"Decatur\n" + 
				"Dickinson\n" + 
				"Doniphan\n" + 
				"Douglas\n" + 
				"Edwards\n" + 
				"Elk\n" + 
				"Ellis\n" + 
				"Ellsworth\n" + 
				"Finney\n" + 
				"Ford\n" + 
				"Franklin\n" + 
				"Geary\n" + 
				"Gove\n" + 
				"Graham\n" + 
				"Grant\n" + 
				"Gray\n" + 
				"Greeley\n" + 
				"Greenwood\n" + 
				"Hamilton\n" + 
				"Harper\n" + 
				"Harvey\n" + 
				"Haskell\n" + 
				"Hodgeman\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Jewell\n" + 
				"Johnson\n" + 
				"Kearny\n" + 
				"Kingman\n" + 
				"Kiowa\n" + 
				"Labette\n" + 
				"Lane\n" + 
				"Leavenworth\n" + 
				"Lincoln\n" + 
				"Linn\n" + 
				"Logan\n" + 
				"Lyon\n" + 
				"McPherson\n" + 
				"Marion\n" + 
				"Marshall\n" + 
				"Meade\n" + 
				"Miami\n" + 
				"Mitchell\n" + 
				"Montgomery\n" + 
				"Morris\n" + 
				"Morton\n" + 
				"Nemaha\n" + 
				"Neosho\n" + 
				"Ness\n" + 
				"Norton\n" + 
				"Osage\n" + 
				"Osborne\n" + 
				"Ottawa\n" + 
				"Pawnee\n" + 
				"Phillips\n" + 
				"Pottawatomie\n" + 
				"Pratt\n" + 
				"Rawlins\n" + 
				"Reno\n" + 
				"Republic\n" + 
				"Rice\n" + 
				"Riley\n" + 
				"Rooks\n" + 
				"Rush\n" + 
				"Russell\n" + 
				"Saline\n" + 
				"Scott\n" + 
				"Sedgwick\n" + 
				"Seward\n" + 
				"Shawnee\n" + 
				"Sheridan\n" + 
				"Sherman\n" + 
				"Smith\n" + 
				"Stafford\n" + 
				"Stanton\n" + 
				"Stevens\n" + 
				"Sumner\n" + 
				"Thomas\n" + 
				"Trego\n" + 
				"Wabaunsee\n" + 
				"Wallace\n" + 
				"Washington\n" + 
				"Wichita\n" + 
				"Wilson\n" + 
				"Woodson\n" + 
				"Wyandotte\n" + 
				"Adair\n" + 
				"Allen\n" + 
				"Anderson\n" + 
				"Ballard\n" + 
				"Barren\n" + 
				"Bath\n" + 
				"Bell\n" + 
				"Boone\n" + 
				"Bourbon\n" + 
				"Boyd\n" + 
				"Boyle\n" + 
				"Bracken\n" + 
				"Breathitt\n" + 
				"Breckinridge\n" + 
				"Bullitt\n" + 
				"Butler\n" + 
				"Caldwell\n" + 
				"Calloway\n" + 
				"Campbell\n" + 
				"Carlisle\n" + 
				"Carroll\n" + 
				"Carter\n" + 
				"Casey\n" + 
				"Christian\n" + 
				"Clark\n" + 
				"Clay\n" + 
				"Clinton\n" + 
				"Crittenden\n" + 
				"Cumberland\n" + 
				"Daviess\n" + 
				"Edmonson\n" + 
				"Elliott\n" + 
				"Estill\n" + 
				"Fayette\n" + 
				"Fleming\n" + 
				"Floyd\n" + 
				"Franklin\n" + 
				"Fulton\n" + 
				"Gallatin\n" + 
				"Garrard\n" + 
				"Grant\n" + 
				"Graves\n" + 
				"Grayson\n" + 
				"Green\n" + 
				"Greenup\n" + 
				"Hancock\n" + 
				"Hardin\n" + 
				"Harlan\n" + 
				"Harrison\n" + 
				"Hart\n" + 
				"Henderson\n" + 
				"Henry\n" + 
				"Hickman\n" + 
				"Hopkins\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Jessamine\n" + 
				"Johnson\n" + 
				"Kenton\n" + 
				"Knott\n" + 
				"Knox\n" + 
				"Larue\n" + 
				"Laurel\n" + 
				"Lawrence\n" + 
				"Lee\n" + 
				"Leslie\n" + 
				"Letcher\n" + 
				"Lewis\n" + 
				"Lincoln\n" + 
				"Livingston\n" + 
				"Logan\n" + 
				"Lyon\n" + 
				"McCracken\n" + 
				"McCreary\n" + 
				"McLean\n" + 
				"Madison\n" + 
				"Magoffin\n" + 
				"Marion\n" + 
				"Marshall\n" + 
				"Martin\n" + 
				"Mason\n" + 
				"Meade\n" + 
				"Menifee\n" + 
				"Mercer\n" + 
				"Metcalfe\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Morgan\n" + 
				"Muhlenberg\n" + 
				"Nelson\n" + 
				"Nicholas\n" + 
				"Ohio\n" + 
				"Oldham\n" + 
				"Owen\n" + 
				"Owsley\n" + 
				"Pendleton\n" + 
				"Perry\n" + 
				"Pike\n" + 
				"Powell\n" + 
				"Pulaski\n" + 
				"Robertson\n" + 
				"Rockcastle\n" + 
				"Rowan\n" + 
				"Russell\n" + 
				"Scott\n" + 
				"Shelby\n" + 
				"Simpson\n" + 
				"Spencer\n" + 
				"Taylor\n" + 
				"Todd\n" + 
				"Trigg\n" + 
				"Trimble\n" + 
				"Union\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Webster\n" + 
				"Whitley\n" + 
				"Wolfe\n" + 
				"Woodford\n" + 
				"Acadia\n" + 
				"Allen\n" + 
				"Ascension\n" + 
				"Assumption\n" + 
				"Avoyelles\n" + 
				"Beauregard\n" + 
				"Bienville\n" + 
				"Bossier\n" + 
				"Caddo\n" + 
				"Calcasieu\n" + 
				"Caldwell\n" + 
				"Cameron\n" + 
				"Catahoula\n" + 
				"Claiborne\n" + 
				"Concordia\n" + 
				"De Soto\n" + 
				"East Baton Rouge\n" + 
				"East Carroll\n" + 
				"East Feliciana\n" + 
				"Evangeline\n" + 
				"Franklin\n" + 
				"Grant\n" + 
				"Iberia\n" + 
				"Iberville\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Jefferson Davis\n" + 
				"Lafayette\n" + 
				"Lafourche\n" + 
				"La Salle\n" + 
				"Lincoln\n" + 
				"Livingston\n" + 
				"Madison\n" + 
				"Morehouse\n" + 
				"Natchitoches\n" + 
				"Orleans\n" + 
				"Ouachita\n" + 
				"Plaquemines\n" + 
				"Pointe Coupee\n" + 
				"Rapides\n" + 
				"Red River\n" + 
				"Richland\n" + 
				"Sabine\n" + 
				"St. Bernard\n" + 
				"St. Charles\n" + 
				"St. Helena\n" + 
				"St. James\n" + 
				"St. John the Baptist\n" + 
				"St. Landry\n" + 
				"St. Martin\n" + 
				"St. Mary\n" + 
				"St. Tammany\n" + 
				"Tangipahoa\n" + 
				"Tensas\n" + 
				"Terrebonne\n" + 
				"Union\n" + 
				"Vermilion\n" + 
				"Vernon\n" + 
				"Washington\n" + 
				"Webster\n" + 
				"West Baton Rouge\n" + 
				"West Carroll\n" + 
				"West Feliciana\n" + 
				"Winn\n" + 
				"Androscoggin\n" + 
				"Aroostook\n" + 
				"Cumberland\n" + 
				"Franklin\n" + 
				"Hancock\n" + 
				"Kennebec\n" + 
				"Knox\n" + 
				"Lincoln\n" + 
				"Oxford\n" + 
				"Penobscot\n" + 
				"Piscataquis\n" + 
				"Sagadahoc\n" + 
				"Somerset\n" + 
				"Waldo\n" + 
				"Washington\n" + 
				"York\n" + 
				"Allegany\n" + 
				"Anne Arundel\n" + 
				"Baltimore\n" + 
				"Calvert\n" + 
				"Caroline\n" + 
				"Carroll\n" + 
				"Cecil\n" + 
				"Charles\n" + 
				"Dorchester\n" + 
				"Frederick\n" + 
				"Garrett\n" + 
				"Harford\n" + 
				"Howard\n" + 
				"Kent\n" + 
				"Montgomery\n" + 
				"Prince George's\n" + 
				"Queen Anne's\n" + 
				"St. Mary's\n" + 
				"Somerset\n" + 
				"Talbot\n" + 
				"Washington\n" + 
				"Wicomico\n" + 
				"Worcester\n" + 
				"Baltimore City\n" + 
				"Barnstable\n" + 
				"Berkshire\n" + 
				"Bristol\n" + 
				"Dukes\n" + 
				"Essex\n" + 
				"Franklin\n" + 
				"Hampden\n" + 
				"Hampshire\n" + 
				"Middlesex\n" + 
				"Nantucket\n" + 
				"Norfolk\n" + 
				"Plymouth\n" + 
				"Suffolk\n" + 
				"Worcester\n" + 
				"Alcona\n" + 
				"Alger\n" + 
				"Allegan\n" + 
				"Alpena\n" + 
				"Antrim\n" + 
				"Arenac\n" + 
				"Baraga\n" + 
				"Barry\n" + 
				"Bay\n" + 
				"Benzie\n" + 
				"Berrien\n" + 
				"Branch\n" + 
				"Calhoun\n" + 
				"Cass\n" + 
				"Charlevoix\n" + 
				"Cheboygan\n" + 
				"Chippewa\n" + 
				"Clare\n" + 
				"Clinton\n" + 
				"Crawford\n" + 
				"Delta\n" + 
				"Dickinson\n" + 
				"Eaton\n" + 
				"Emmet\n" + 
				"Genesee\n" + 
				"Gladwin\n" + 
				"Gogebic\n" + 
				"Grand Traverse\n" + 
				"Gratiot\n" + 
				"Hillsdale\n" + 
				"Houghton\n" + 
				"Huron\n" + 
				"Ingham\n" + 
				"Ionia\n" + 
				"Iosco\n" + 
				"Iron\n" + 
				"Isabella\n" + 
				"Jackson\n" + 
				"Kalamazoo\n" + 
				"Kalkaska\n" + 
				"Kent\n" + 
				"Keweenaw\n" + 
				"Lake\n" + 
				"Lapeer\n" + 
				"Leelanau\n" + 
				"Lenawee\n" + 
				"Livingston\n" + 
				"Luce\n" + 
				"Mackinac\n" + 
				"Macomb\n" + 
				"Manistee\n" + 
				"Marquette\n" + 
				"Mason\n" + 
				"Mecosta\n" + 
				"Menominee\n" + 
				"Midland\n" + 
				"Missaukee\n" + 
				"Monroe\n" + 
				"Montcalm\n" + 
				"Montmorency\n" + 
				"Muskegon\n" + 
				"Newaygo\n" + 
				"Oakland\n" + 
				"Oceana\n" + 
				"Ogemaw\n" + 
				"Ontonagon\n" + 
				"Osceola\n" + 
				"Oscoda\n" + 
				"Otsego\n" + 
				"Ottawa\n" + 
				"Presque Isle\n" + 
				"Roscommon\n" + 
				"Saginaw\n" + 
				"St. Clair\n" + 
				"St. Joseph\n" + 
				"Sanilac\n" + 
				"Schoolcraft\n" + 
				"Shiawassee\n" + 
				"Tuscola\n" + 
				"Van Buren\n" + 
				"Washtenaw\n" + 
				"Wayne\n" + 
				"Wexford\n" + 
				"Aitkin\n" + 
				"Anoka\n" + 
				"Becker\n" + 
				"Beltrami\n" + 
				"Benton\n" + 
				"Big Stone\n" + 
				"Blue Earth\n" + 
				"Brown\n" + 
				"Carlton\n" + 
				"Carver\n" + 
				"Cass\n" + 
				"Chippewa\n" + 
				"Chisago\n" + 
				"Clay\n" + 
				"Clearwater\n" + 
				"Cook\n" + 
				"Cottonwood\n" + 
				"Crow Wing\n" + 
				"Dakota\n" + 
				"Dodge\n" + 
				"Douglas\n" + 
				"Faribault\n" + 
				"Fillmore\n" + 
				"Freeborn\n" + 
				"Goodhue\n" + 
				"Grant\n" + 
				"Hennepin\n" + 
				"Houston\n" + 
				"Hubbard\n" + 
				"Isanti\n" + 
				"Itasca\n" + 
				"Jackson\n" + 
				"Kanabec\n" + 
				"Kandiyohi\n" + 
				"Kittson\n" + 
				"Koochiching\n" + 
				"Lac Qui Parle\n" + 
				"Lake\n" + 
				"Lake of the Woods\n" + 
				"Le Sueur\n" + 
				"Lincoln\n" + 
				"Lyon\n" + 
				"McLeod\n" + 
				"Mahnomen\n" + 
				"Marshall\n" + 
				"Martin\n" + 
				"Meeker\n" + 
				"Mille Lacs\n" + 
				"Morrison\n" + 
				"Mower\n" + 
				"Murray\n" + 
				"Nicollet\n" + 
				"Nobles\n" + 
				"Norman\n" + 
				"Olmsted\n" + 
				"Otter Tail\n" + 
				"Pennington\n" + 
				"Pine\n" + 
				"Pipestone\n" + 
				"Polk\n" + 
				"Pope\n" + 
				"Ramsey\n" + 
				"Red Lake\n" + 
				"Redwood\n" + 
				"Renville\n" + 
				"Rice\n" + 
				"Rock\n" + 
				"Roseau\n" + 
				"Saint Louis\n" + 
				"Scott\n" + 
				"Sherburne\n" + 
				"Sibley\n" + 
				"Stearns\n" + 
				"Steele\n" + 
				"Stevens\n" + 
				"Swift\n" + 
				"Todd\n" + 
				"Traverse\n" + 
				"Wabasha\n" + 
				"Wadena\n" + 
				"Waseca\n" + 
				"Washington\n" + 
				"Watonwan\n" + 
				"Wilkin\n" + 
				"Winona\n" + 
				"Wright\n" + 
				"Yellow Medicine\n" + 
				"Adams\n" + 
				"Alcorn\n" + 
				"Amite\n" + 
				"Attala\n" + 
				"Benton\n" + 
				"Bolivar\n" + 
				"Calhoun\n" + 
				"Carroll\n" + 
				"Chickasaw\n" + 
				"Choctaw\n" + 
				"Claiborne\n" + 
				"Clarke\n" + 
				"Clay\n" + 
				"Coahoma\n" + 
				"Copiah\n" + 
				"Covington\n" + 
				"DeSoto\n" + 
				"Forrest\n" + 
				"Franklin\n" + 
				"George\n" + 
				"Greene\n" + 
				"Grenada\n" + 
				"Hancock\n" + 
				"Harrison\n" + 
				"Hinds\n" + 
				"Holmes\n" + 
				"Humphreys\n" + 
				"Issaquena\n" + 
				"Itawamba\n" + 
				"Jackson\n" + 
				"Jasper\n" + 
				"Jefferson\n" + 
				"Jefferson Davis\n" + 
				"Jones\n" + 
				"Kemper\n" + 
				"Lafayette\n" + 
				"Lamar\n" + 
				"Lauderdale\n" + 
				"Lawrence\n" + 
				"Leake\n" + 
				"Lee\n" + 
				"Leflore\n" + 
				"Lincoln\n" + 
				"Lowndes\n" + 
				"Madison\n" + 
				"Marion\n" + 
				"Marshall\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Neshoba\n" + 
				"Newton\n" + 
				"Noxubee\n" + 
				"Oktibbeha\n" + 
				"Panola\n" + 
				"Pearl River\n" + 
				"Perry\n" + 
				"Pike\n" + 
				"Pontotoc\n" + 
				"Prentiss\n" + 
				"Quitman\n" + 
				"Rankin\n" + 
				"Scott\n" + 
				"Sharkey\n" + 
				"Simpson\n" + 
				"Smith\n" + 
				"Stone\n" + 
				"Sunflower\n" + 
				"Tallahatchie\n" + 
				"Tate\n" + 
				"Tippah\n" + 
				"Tishomingo\n" + 
				"Tunica\n" + 
				"Union\n" + 
				"Walthall\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Webster\n" + 
				"Wilkinson\n" + 
				"Winston\n" + 
				"Yalobusha\n" + 
				"Yazoo\n" + 
				"Adair\n" + 
				"Andrew\n" + 
				"Atchison\n" + 
				"Audrain\n" + 
				"Barry\n" + 
				"Barton\n" + 
				"Bates\n" + 
				"Benton\n" + 
				"Bollinger\n" + 
				"Boone\n" + 
				"Buchanan\n" + 
				"Butler\n" + 
				"Caldwell\n" + 
				"Callaway\n" + 
				"Camden\n" + 
				"Cape Girardeau\n" + 
				"Carroll\n" + 
				"Carter\n" + 
				"Cass\n" + 
				"Cedar\n" + 
				"Chariton\n" + 
				"Christian\n" + 
				"Clark\n" + 
				"Clay\n" + 
				"Clinton\n" + 
				"Cole\n" + 
				"Cooper\n" + 
				"Crawford\n" + 
				"Dade\n" + 
				"Dallas\n" + 
				"Daviess\n" + 
				"DeKalb\n" + 
				"Dent\n" + 
				"Douglas\n" + 
				"Dunklin\n" + 
				"Franklin\n" + 
				"Gasconade\n" + 
				"Gentry\n" + 
				"Greene\n" + 
				"Grundy\n" + 
				"Harrison\n" + 
				"Henry\n" + 
				"Hickory\n" + 
				"Holt\n" + 
				"Howard\n" + 
				"Howell\n" + 
				"Iron\n" + 
				"Jackson\n" + 
				"Jasper\n" + 
				"Jefferson\n" + 
				"Johnson\n" + 
				"Knox\n" + 
				"Laclede\n" + 
				"Lafayette\n" + 
				"Lawrence\n" + 
				"Lewis\n" + 
				"Lincoln\n" + 
				"Linn\n" + 
				"Livingston\n" + 
				"McDonald\n" + 
				"Macon\n" + 
				"Madison\n" + 
				"Maries\n" + 
				"Marion\n" + 
				"Mercer\n" + 
				"Miller\n" + 
				"Mississippi\n" + 
				"Moniteau\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Morgan\n" + 
				"New Madrid\n" + 
				"Newton\n" + 
				"Nodaway\n" + 
				"Oregon\n" + 
				"Osage\n" + 
				"Ozark\n" + 
				"Pemiscot\n" + 
				"Perry\n" + 
				"Pettis\n" + 
				"Phelps\n" + 
				"Pike\n" + 
				"Platte\n" + 
				"Polk\n" + 
				"Pulaski\n" + 
				"Putnam\n" + 
				"Ralls\n" + 
				"Randolph\n" + 
				"Ray\n" + 
				"Reynolds\n" + 
				"Ripley\n" + 
				"St. Charles\n" + 
				"St. Clair\n" + 
				"Ste. Genevieve\n" + 
				"St. Francois\n" + 
				"St. Louis County\n" + 
				"Saline\n" + 
				"Schuyler\n" + 
				"Scotland\n" + 
				"Scott\n" + 
				"Shannon\n" + 
				"Shelby\n" + 
				"Stoddard\n" + 
				"Stone\n" + 
				"Sullivan\n" + 
				"Taney\n" + 
				"Texas\n" + 
				"Vernon\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Webster\n" + 
				"Worth\n" + 
				"Wright\n" + 
				"St. Louis City\n" + 
				"Beaverhead\n" + 
				"Big Horn\n" + 
				"Blaine\n" + 
				"Broadwater\n" + 
				"Carbon\n" + 
				"Carter\n" + 
				"Cascade\n" + 
				"Chouteau\n" + 
				"Custer\n" + 
				"Daniels\n" + 
				"Dawson\n" + 
				"Deer Lodge\n" + 
				"Fallon\n" + 
				"Fergus\n" + 
				"Flathead\n" + 
				"Gallatin\n" + 
				"Garfield\n" + 
				"Glacier\n" + 
				"Golden Valley\n" + 
				"Granite\n" + 
				"Hill\n" + 
				"Jefferson\n" + 
				"Judith Basin\n" + 
				"Lake\n" + 
				"Lewis and Clark\n" + 
				"Liberty\n" + 
				"Lincoln\n" + 
				"McCone\n" + 
				"Madison\n" + 
				"Meagher\n" + 
				"Mineral\n" + 
				"Missoula\n" + 
				"Musselshell\n" + 
				"Park\n" + 
				"Petroleum\n" + 
				"Phillips\n" + 
				"Pondera\n" + 
				"Powder River\n" + 
				"Powell\n" + 
				"Prairie\n" + 
				"Ravalli\n" + 
				"Richland\n" + 
				"Roosevelt\n" + 
				"Rosebud\n" + 
				"Sanders\n" + 
				"Sheridan\n" + 
				"Silver Bow\n" + 
				"Stillwater\n" + 
				"Sweet Grass\n" + 
				"Teton\n" + 
				"Toole\n" + 
				"Treasure\n" + 
				"Valley\n" + 
				"Wheatland\n" + 
				"Wibaux\n" + 
				"Yellowstone\n" + 
				"Adams\n" + 
				"Antelope\n" + 
				"Arthur\n" + 
				"Banner\n" + 
				"Blaine\n" + 
				"Boone\n" + 
				"Box Butte\n" + 
				"Boyd\n" + 
				"Brown\n" + 
				"Buffalo\n" + 
				"Burt\n" + 
				"Butler\n" + 
				"Cass\n" + 
				"Cedar\n" + 
				"Chase\n" + 
				"Cherry\n" + 
				"Cheyenne\n" + 
				"Clay\n" + 
				"Colfax\n" + 
				"Cuming\n" + 
				"Custer\n" + 
				"Dakota\n" + 
				"Dawes\n" + 
				"Dawson\n" + 
				"Deuel\n" + 
				"Dixon\n" + 
				"Dodge\n" + 
				"Douglas\n" + 
				"Dundy\n" + 
				"Fillmore\n" + 
				"Franklin\n" + 
				"Frontier\n" + 
				"Furnas\n" + 
				"Gage\n" + 
				"Garden\n" + 
				"Garfield\n" + 
				"Gosper\n" + 
				"Grant\n" + 
				"Greeley\n" + 
				"Hall\n" + 
				"Hamilton\n" + 
				"Harlan\n" + 
				"Hayes\n" + 
				"Hitchcock\n" + 
				"Holt\n" + 
				"Hooker\n" + 
				"Howard\n" + 
				"Jefferson\n" + 
				"Johnson\n" + 
				"Kearney\n" + 
				"Keith\n" + 
				"Keya Paha\n" + 
				"Kimball\n" + 
				"Knox\n" + 
				"Lancaster\n" + 
				"Lincoln\n" + 
				"Logan\n" + 
				"Loup\n" + 
				"McPherson\n" + 
				"Madison\n" + 
				"Merrick\n" + 
				"Morrill\n" + 
				"Nance\n" + 
				"Nemaha\n" + 
				"Nuckolls\n" + 
				"Otoe\n" + 
				"Pawnee\n" + 
				"Perkins\n" + 
				"Phelps\n" + 
				"Pierce\n" + 
				"Platte\n" + 
				"Polk\n" + 
				"Red Willow\n" + 
				"Richardson\n" + 
				"Rock\n" + 
				"Saline\n" + 
				"Sarpy\n" + 
				"Saunders\n" + 
				"Scotts Bluff\n" + 
				"Seward\n" + 
				"Sheridan\n" + 
				"Sherman\n" + 
				"Sioux\n" + 
				"Stanton\n" + 
				"Thayer\n" + 
				"Thomas\n" + 
				"Thurston\n" + 
				"Valley\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Webster\n" + 
				"Wheeler\n" + 
				"York\n" + 
				"Churchill\n" + 
				"Clark\n" + 
				"Douglas\n" + 
				"Elko\n" + 
				"Esmeralda\n" + 
				"Eureka\n" + 
				"Humboldt\n" + 
				"Lander\n" + 
				"Lincoln\n" + 
				"Lyon\n" + 
				"Mineral\n" + 
				"Nye\n" + 
				"Pershing\n" + 
				"Storey\n" + 
				"Washoe\n" + 
				"White Pine\n" + 
				"Carson City\n" + 
				"Belknap\n" + 
				"Carroll\n" + 
				"Cheshire\n" + 
				"Coos\n" + 
				"Grafton\n" + 
				"Hillsborough\n" + 
				"Merrimack\n" + 
				"Rockingham\n" + 
				"Strafford\n" + 
				"Sullivan\n" + 
				"Atlantic\n" + 
				"Bergen\n" + 
				"Burlington\n" + 
				"Camden\n" + 
				"Cape May\n" + 
				"Cumberland\n" + 
				"Essex\n" + 
				"Gloucester\n" + 
				"Hudson\n" + 
				"Hunterdon\n" + 
				"Mercer\n" + 
				"Middlesex\n" + 
				"Monmouth\n" + 
				"Morris\n" + 
				"Ocean\n" + 
				"Passaic\n" + 
				"Salem\n" + 
				"Somerset\n" + 
				"Sussex\n" + 
				"Union\n" + 
				"Warren\n" + 
				"Bernalillo\n" + 
				"Catron\n" + 
				"Chaves\n" + 
				"Cibola\n" + 
				"Colfax\n" + 
				"Curry\n" + 
				"De Baca\n" + 
				"Dona Ana\n" + 
				"Eddy\n" + 
				"Grant\n" + 
				"Guadalupe\n" + 
				"Harding\n" + 
				"Hidalgo\n" + 
				"Lea\n" + 
				"Lincoln\n" + 
				"Los Alamos\n" + 
				"Luna\n" + 
				"McKinley\n" + 
				"Mora\n" + 
				"Otero\n" + 
				"Quay\n" + 
				"Rio Arriba\n" + 
				"Roosevelt\n" + 
				"Sandoval\n" + 
				"San Juan\n" + 
				"San Miguel\n" + 
				"Santa Fe\n" + 
				"Sierra\n" + 
				"Socorro\n" + 
				"Taos\n" + 
				"Torrance\n" + 
				"Union\n" + 
				"Valencia\n" + 
				"Albany\n" + 
				"Allegany\n" + 
				"Bronx\n" + 
				"Broome\n" + 
				"Cattaraugus\n" + 
				"Cayuga\n" + 
				"Chautauqua\n" + 
				"Chemung\n" + 
				"Chenango\n" + 
				"Clinton\n" + 
				"Columbia\n" + 
				"Cortland\n" + 
				"Delaware\n" + 
				"Dutchess\n" + 
				"Erie\n" + 
				"Essex\n" + 
				"Franklin\n" + 
				"Fulton\n" + 
				"Genesee\n" + 
				"Greene\n" + 
				"Hamilton\n" + 
				"Herkimer\n" + 
				"Jefferson\n" + 
				"Kings\n" + 
				"Lewis\n" + 
				"Livingston\n" + 
				"Madison\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Nassau\n" + 
				"New York\n" + 
				"Niagara\n" + 
				"Oneida\n" + 
				"Onondaga\n" + 
				"Ontario\n" + 
				"Orange\n" + 
				"Orleans\n" + 
				"Oswego\n" + 
				"Otsego\n" + 
				"Putnam\n" + 
				"Queens\n" + 
				"Rensselaer\n" + 
				"Richmond\n" + 
				"Rockland\n" + 
				"St. Lawrence\n" + 
				"Saratoga\n" + 
				"Schenectady\n" + 
				"Schoharie\n" + 
				"Schuyler\n" + 
				"Seneca\n" + 
				"Steuben\n" + 
				"Suffolk\n" + 
				"Sullivan\n" + 
				"Tioga\n" + 
				"Tompkins\n" + 
				"Ulster\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Westchester\n" + 
				"Wyoming\n" + 
				"Yates\n" + 
				"Alamance\n" + 
				"Alexander\n" + 
				"Alleghany\n" + 
				"Anson\n" + 
				"Ashe\n" + 
				"Avery\n" + 
				"Beaufort\n" + 
				"Bertie\n" + 
				"Bladen\n" + 
				"Brunswick\n" + 
				"Buncombe\n" + 
				"Burke\n" + 
				"Cabarrus\n" + 
				"Caldwell\n" + 
				"Camden\n" + 
				"Carteret\n" + 
				"Caswell\n" + 
				"Catawba\n" + 
				"Chatham\n" + 
				"Cherokee\n" + 
				"Chowan\n" + 
				"Clay\n" + 
				"Cleveland\n" + 
				"Columbus\n" + 
				"Craven\n" + 
				"Cumberland\n" + 
				"Currituck\n" + 
				"Dare\n" + 
				"Davidson\n" + 
				"Davie\n" + 
				"Duplin\n" + 
				"Durham\n" + 
				"Edgecombe\n" + 
				"Forsyth\n" + 
				"Franklin\n" + 
				"Gaston\n" + 
				"Gates\n" + 
				"Graham\n" + 
				"Granville\n" + 
				"Greene\n" + 
				"Guilford\n" + 
				"Halifax\n" + 
				"Harnett\n" + 
				"Haywood\n" + 
				"Henderson\n" + 
				"Hertford\n" + 
				"Hoke\n" + 
				"Hyde\n" + 
				"Iredell\n" + 
				"Jackson\n" + 
				"Johnston\n" + 
				"Jones\n" + 
				"Lee\n" + 
				"Lenoir\n" + 
				"Lincoln\n" + 
				"McDowell\n" + 
				"Macon\n" + 
				"Madison\n" + 
				"Martin\n" + 
				"Mecklenburg\n" + 
				"Mitchell\n" + 
				"Montgomery\n" + 
				"Moore\n" + 
				"Nash\n" + 
				"New Hanover\n" + 
				"Northampton\n" + 
				"Onslow\n" + 
				"Orange\n" + 
				"Pamlico\n" + 
				"Pasquotank\n" + 
				"Pender\n" + 
				"Perquimans\n" + 
				"Person\n" + 
				"Pitt\n" + 
				"Polk\n" + 
				"Randolph\n" + 
				"Richmond\n" + 
				"Robeson\n" + 
				"Rockingham\n" + 
				"Rowan\n" + 
				"Rutherford\n" + 
				"Sampson\n" + 
				"Scotland\n" + 
				"Stanly\n" + 
				"Stokes\n" + 
				"Surry\n" + 
				"Swain\n" + 
				"Transylvania\n" + 
				"Tyrrell\n" + 
				"Union\n" + 
				"Vance\n" + 
				"Wake\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Watauga\n" + 
				"Wayne\n" + 
				"Wilkes\n" + 
				"Wilson\n" + 
				"Yadkin\n" + 
				"Yancey\n" + 
				"Adams\n" + 
				"Barnes\n" + 
				"Benson\n" + 
				"Billings\n" + 
				"Bottineau\n" + 
				"Bowman\n" + 
				"Burke\n" + 
				"Burleigh\n" + 
				"Cass\n" + 
				"Cavalier\n" + 
				"Dickey\n" + 
				"Divide\n" + 
				"Dunn\n" + 
				"Eddy\n" + 
				"Emmons\n" + 
				"Foster\n" + 
				"Golden Valley\n" + 
				"Grand Forks\n" + 
				"Grant\n" + 
				"Griggs\n" + 
				"Hettinger\n" + 
				"Kidder\n" + 
				"LaMoure\n" + 
				"Logan\n" + 
				"McHenry\n" + 
				"McIntosh\n" + 
				"McKenzie\n" + 
				"McLean\n" + 
				"Mercer\n" + 
				"Morton\n" + 
				"Mountrail\n" + 
				"Nelson\n" + 
				"Oliver\n" + 
				"Pembina\n" + 
				"Pierce\n" + 
				"Ramsey\n" + 
				"Ransom\n" + 
				"Renville\n" + 
				"Richland\n" + 
				"Rolette\n" + 
				"Sargent\n" + 
				"Sheridan\n" + 
				"Sioux\n" + 
				"Slope\n" + 
				"Stark\n" + 
				"Steele\n" + 
				"Stutsman\n" + 
				"Towner\n" + 
				"Traill\n" + 
				"Walsh\n" + 
				"Ward\n" + 
				"Wells\n" + 
				"Williams\n" + 
				"Adams\n" + 
				"Allen\n" + 
				"Ashland\n" + 
				"Ashtabula\n" + 
				"Athens\n" + 
				"Auglaize\n" + 
				"Belmont\n" + 
				"Brown\n" + 
				"Butler\n" + 
				"Carroll\n" + 
				"Champaign\n" + 
				"Clark\n" + 
				"Clermont\n" + 
				"Clinton\n" + 
				"Columbiana\n" + 
				"Coshocton\n" + 
				"Crawford\n" + 
				"Cuyahoga\n" + 
				"Darke\n" + 
				"Defiance\n" + 
				"Delaware\n" + 
				"Erie\n" + 
				"Fairfield\n" + 
				"Fayette\n" + 
				"Franklin\n" + 
				"Fulton\n" + 
				"Gallia\n" + 
				"Geauga\n" + 
				"Greene\n" + 
				"Guernsey\n" + 
				"Hamilton\n" + 
				"Hancock\n" + 
				"Hardin\n" + 
				"Harrison\n" + 
				"Henry\n" + 
				"Highland\n" + 
				"Hocking\n" + 
				"Holmes\n" + 
				"Huron\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Knox\n" + 
				"Lake\n" + 
				"Lawrence\n" + 
				"Licking\n" + 
				"Logan\n" + 
				"Lorain\n" + 
				"Lucas\n" + 
				"Madison\n" + 
				"Mahoning\n" + 
				"Marion\n" + 
				"Medina\n" + 
				"Meigs\n" + 
				"Mercer\n" + 
				"Miami\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Morgan\n" + 
				"Morrow\n" + 
				"Muskingum\n" + 
				"Noble\n" + 
				"Ottawa\n" + 
				"Paulding\n" + 
				"Perry\n" + 
				"Pickaway\n" + 
				"Pike\n" + 
				"Portage\n" + 
				"Preble\n" + 
				"Putnam\n" + 
				"Richland\n" + 
				"Ross\n" + 
				"Sandusky\n" + 
				"Scioto\n" + 
				"Seneca\n" + 
				"Shelby\n" + 
				"Stark\n" + 
				"Summit\n" + 
				"Trumbull\n" + 
				"Tuscarawas\n" + 
				"Union\n" + 
				"Van Wert\n" + 
				"Vinton\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Williams\n" + 
				"Wood\n" + 
				"Wyandot\n" + 
				"Adair\n" + 
				"Alfalfa\n" + 
				"Atoka\n" + 
				"Beaver\n" + 
				"Beckham\n" + 
				"Blaine\n" + 
				"Bryan\n" + 
				"Caddo\n" + 
				"Canadian\n" + 
				"Carter\n" + 
				"Cherokee\n" + 
				"Choctaw\n" + 
				"Cimarron\n" + 
				"Cleveland\n" + 
				"Coal\n" + 
				"Comanche\n" + 
				"Cotton\n" + 
				"Craig\n" + 
				"Creek\n" + 
				"Custer\n" + 
				"Delaware\n" + 
				"Dewey\n" + 
				"Ellis\n" + 
				"Garfield\n" + 
				"Garvin\n" + 
				"Grady\n" + 
				"Grant\n" + 
				"Greer\n" + 
				"Harmon\n" + 
				"Harper\n" + 
				"Haskell\n" + 
				"Hughes\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Johnston\n" + 
				"Kay\n" + 
				"Kingfisher\n" + 
				"Kiowa\n" + 
				"Latimer\n" + 
				"Le Flore\n" + 
				"Lincoln\n" + 
				"Logan\n" + 
				"Love\n" + 
				"McClain\n" + 
				"McCurtain\n" + 
				"McIntosh\n" + 
				"Major\n" + 
				"Marshall\n" + 
				"Mayes\n" + 
				"Murray\n" + 
				"Muskogee\n" + 
				"Noble\n" + 
				"Nowata\n" + 
				"Okfuskee\n" + 
				"Oklahoma\n" + 
				"Okmulgee\n" + 
				"Osage\n" + 
				"Ottawa\n" + 
				"Pawnee\n" + 
				"Payne\n" + 
				"Pittsburg\n" + 
				"Pontotoc\n" + 
				"Pottawatomie\n" + 
				"Pushmataha\n" + 
				"Roger Mills\n" + 
				"Rogers\n" + 
				"Seminole\n" + 
				"Sequoyah\n" + 
				"Stephens\n" + 
				"Texas\n" + 
				"Tillman\n" + 
				"Tulsa\n" + 
				"Wagoner\n" + 
				"Washington\n" + 
				"Washita\n" + 
				"Woods\n" + 
				"Woodward\n" + 
				"Baker\n" + 
				"Benton\n" + 
				"Clackamas\n" + 
				"Clatsop\n" + 
				"Columbia\n" + 
				"Coos\n" + 
				"Crook\n" + 
				"Curry\n" + 
				"Deschutes\n" + 
				"Douglas\n" + 
				"Gilliam\n" + 
				"Grant\n" + 
				"Harney\n" + 
				"Hood River\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Josephine\n" + 
				"Klamath\n" + 
				"Lake\n" + 
				"Lane\n" + 
				"Lincoln\n" + 
				"Linn\n" + 
				"Malheur\n" + 
				"Marion\n" + 
				"Morrow\n" + 
				"Multnomah\n" + 
				"Polk\n" + 
				"Sherman\n" + 
				"Tillamook\n" + 
				"Umatilla\n" + 
				"Union\n" + 
				"Wallowa\n" + 
				"Wasco\n" + 
				"Washington\n" + 
				"Wheeler\n" + 
				"Yamhill\n" + 
				"Adams\n" + 
				"Allegheny\n" + 
				"Armstrong\n" + 
				"Beaver\n" + 
				"Berks\n" + 
				"Blair\n" + 
				"Bradford\n" + 
				"Bucks\n" + 
				"Butler\n" + 
				"Cambria\n" + 
				"Cameron\n" + 
				"Carbon\n" + 
				"Centre\n" + 
				"Chester\n" + 
				"Clarion\n" + 
				"Clearfield\n" + 
				"Clinton\n" + 
				"Columbia\n" + 
				"Crawford\n" + 
				"Cumberland\n" + 
				"Dauphin\n" + 
				"Delaware\n" + 
				"Elk\n" + 
				"Erie\n" + 
				"Fayette\n" + 
				"Forest\n" + 
				"Franklin\n" + 
				"Fulton\n" + 
				"Greene\n" + 
				"Huntingdon\n" + 
				"Indiana\n" + 
				"Jefferson\n" + 
				"Juniata\n" + 
				"Lackawanna\n" + 
				"Lancaster\n" + 
				"Lawrence\n" + 
				"Lebanon\n" + 
				"Lehigh\n" + 
				"Luzerne\n" + 
				"Lycoming\n" + 
				"McKean\n" + 
				"Mercer\n" + 
				"Mifflin\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Montour\n" + 
				"Northampton\n" + 
				"Northumberland\n" + 
				"Perry\n" + 
				"Philadelphia\n" + 
				"Pike\n" + 
				"Potter\n" + 
				"Schuylkill\n" + 
				"Snyder\n" + 
				"Somerset\n" + 
				"Sullivan\n" + 
				"Susquehanna\n" + 
				"Tioga\n" + 
				"Union\n" + 
				"Venango\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Westmoreland\n" + 
				"Wyoming\n" + 
				"York\n" + 
				"Bristol\n" + 
				"Kent\n" + 
				"Newport\n" + 
				"Providence\n" + 
				"Washington\n" + 
				"Abbeville\n" + 
				"Aiken\n" + 
				"Allendale\n" + 
				"Anderson\n" + 
				"Bamberg\n" + 
				"Barnwell\n" + 
				"Beaufort\n" + 
				"Berkeley\n" + 
				"Calhoun\n" + 
				"Charleston\n" + 
				"Cherokee\n" + 
				"Chester\n" + 
				"Chesterfield\n" + 
				"Clarendon\n" + 
				"Colleton\n" + 
				"Darlington\n" + 
				"Dillon\n" + 
				"Dorchester\n" + 
				"Edgefield\n" + 
				"Fairfield\n" + 
				"Florence\n" + 
				"Georgetown\n" + 
				"Greenville\n" + 
				"Greenwood\n" + 
				"Hampton\n" + 
				"Horry\n" + 
				"Jasper\n" + 
				"Kershaw\n" + 
				"Lancaster\n" + 
				"Laurens\n" + 
				"Lee\n" + 
				"Lexington\n" + 
				"McCormick\n" + 
				"Marion\n" + 
				"Marlboro\n" + 
				"Newberry\n" + 
				"Oconee\n" + 
				"Orangeburg\n" + 
				"Pickens\n" + 
				"Richland\n" + 
				"Saluda\n" + 
				"Spartanburg\n" + 
				"Sumter\n" + 
				"Union\n" + 
				"Williamsburg\n" + 
				"York\n" + 
				"Aurora\n" + 
				"Beadle\n" + 
				"Bennett\n" + 
				"Bon Homme\n" + 
				"Brookings\n" + 
				"Brown\n" + 
				"Brule\n" + 
				"Buffalo\n" + 
				"Butte\n" + 
				"Campbell\n" + 
				"Charles Mix\n" + 
				"Clark\n" + 
				"Clay\n" + 
				"Codington\n" + 
				"Corson\n" + 
				"Custer\n" + 
				"Davison\n" + 
				"Day\n" + 
				"Deuel\n" + 
				"Dewey\n" + 
				"Douglas\n" + 
				"Edmunds\n" + 
				"Fall River\n" + 
				"Faulk\n" + 
				"Grant\n" + 
				"Gregory\n" + 
				"Haakon\n" + 
				"Hamlin\n" + 
				"Hand\n" + 
				"Hanson\n" + 
				"Harding\n" + 
				"Hughes\n" + 
				"Hutchinson\n" + 
				"Hyde\n" + 
				"Jackson\n" + 
				"Jerauld\n" + 
				"Jones\n" + 
				"Kingsbury\n" + 
				"Lake\n" + 
				"Lawrence\n" + 
				"Lincoln\n" + 
				"Lyman\n" + 
				"McCook\n" + 
				"McPherson\n" + 
				"Marshall\n" + 
				"Meade\n" + 
				"Mellette\n" + 
				"Miner\n" + 
				"Minnehaha\n" + 
				"Moody\n" + 
				"Pennington\n" + 
				"Perkins\n" + 
				"Potter\n" + 
				"Roberts\n" + 
				"Sanborn\n" + 
				"Oglala Lakota\n" + 
				"Spink\n" + 
				"Stanley\n" + 
				"Sully\n" + 
				"Todd\n" + 
				"Tripp\n" + 
				"Turner\n" + 
				"Union\n" + 
				"Walworth\n" + 
				"Yankton\n" + 
				"Ziebach\n" + 
				"Bedford\n" + 
				"Benton\n" + 
				"Bledsoe\n" + 
				"Blount\n" + 
				"Bradley\n" + 
				"Campbell\n" + 
				"Cannon\n" + 
				"Carroll\n" + 
				"Carter\n" + 
				"Cheatham\n" + 
				"Chester\n" + 
				"Claiborne\n" + 
				"Clay\n" + 
				"Cocke\n" + 
				"Coffee\n" + 
				"Crockett\n" + 
				"Cumberland\n" + 
				"Davidson\n" + 
				"Decatur\n" + 
				"DeKalb\n" + 
				"Dickson\n" + 
				"Dyer\n" + 
				"Fayette\n" + 
				"Fentress\n" + 
				"Franklin\n" + 
				"Gibson\n" + 
				"Giles\n" + 
				"Grainger\n" + 
				"Greene\n" + 
				"Grundy\n" + 
				"Hamblen\n" + 
				"Hamilton\n" + 
				"Hancock\n" + 
				"Hardeman\n" + 
				"Hardin\n" + 
				"Hawkins\n" + 
				"Haywood\n" + 
				"Henderson\n" + 
				"Henry\n" + 
				"Hickman\n" + 
				"Houston\n" + 
				"Humphreys\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Johnson\n" + 
				"Knox\n" + 
				"Lake\n" + 
				"Lauderdale\n" + 
				"Lawrence\n" + 
				"Lewis\n" + 
				"Lincoln\n" + 
				"Loudon\n" + 
				"McMinn\n" + 
				"McNairy\n" + 
				"Macon\n" + 
				"Madison\n" + 
				"Marion\n" + 
				"Marshall\n" + 
				"Maury\n" + 
				"Meigs\n" + 
				"Monroe\n" + 
				"Montgomery\n" + 
				"Moore\n" + 
				"Morgan\n" + 
				"Obion\n" + 
				"Overton\n" + 
				"Perry\n" + 
				"Pickett\n" + 
				"Polk\n" + 
				"Putnam\n" + 
				"Rhea\n" + 
				"Roane\n" + 
				"Robertson\n" + 
				"Rutherford\n" + 
				"Scott\n" + 
				"Sequatchie\n" + 
				"Sevier\n" + 
				"Shelby\n" + 
				"Smith\n" + 
				"Stewart\n" + 
				"Sullivan\n" + 
				"Sumner\n" + 
				"Tipton\n" + 
				"Trousdale\n" + 
				"Unicoi\n" + 
				"Union\n" + 
				"Van Buren\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Weakley\n" + 
				"White\n" + 
				"Williamson\n" + 
				"Wilson\n" + 
				"Anderson\n" + 
				"Andrews\n" + 
				"Angelina\n" + 
				"Aransas\n" + 
				"Archer\n" + 
				"Armstrong\n" + 
				"Atascosa\n" + 
				"Austin\n" + 
				"Bailey\n" + 
				"Bandera\n" + 
				"Bastrop\n" + 
				"Baylor\n" + 
				"Bee\n" + 
				"Bell\n" + 
				"Bexar\n" + 
				"Blanco\n" + 
				"Borden\n" + 
				"Bosque\n" + 
				"Bowie\n" + 
				"Brazoria\n" + 
				"Brazos\n" + 
				"Brewster\n" + 
				"Briscoe\n" + 
				"Brooks\n" + 
				"Brown\n" + 
				"Burleson\n" + 
				"Burnet\n" + 
				"Caldwell\n" + 
				"Calhoun\n" + 
				"Callahan\n" + 
				"Cameron\n" + 
				"Camp\n" + 
				"Carson\n" + 
				"Cass\n" + 
				"Castro\n" + 
				"Chambers\n" + 
				"Cherokee\n" + 
				"Childress\n" + 
				"Clay\n" + 
				"Cochran\n" + 
				"Coke\n" + 
				"Coleman\n" + 
				"Collin\n" + 
				"Collingsworth\n" + 
				"Colorado\n" + 
				"Comal\n" + 
				"Comanche\n" + 
				"Concho\n" + 
				"Cooke\n" + 
				"Coryell\n" + 
				"Cottle\n" + 
				"Crane\n" + 
				"Crockett\n" + 
				"Crosby\n" + 
				"Culberson\n" + 
				"Dallam\n" + 
				"Dallas\n" + 
				"Dawson\n" + 
				"Deaf Smith\n" + 
				"Delta\n" + 
				"Denton\n" + 
				"Dewitt\n" + 
				"Dickens\n" + 
				"Dimmit\n" + 
				"Donley\n" + 
				"Duval\n" + 
				"Eastland\n" + 
				"Ector\n" + 
				"Edwards\n" + 
				"Ellis\n" + 
				"El Paso\n" + 
				"Erath\n" + 
				"Falls\n" + 
				"Fannin\n" + 
				"Fayette\n" + 
				"Fisher\n" + 
				"Floyd\n" + 
				"Foard\n" + 
				"Fort Bend\n" + 
				"Franklin\n" + 
				"Freestone\n" + 
				"Frio\n" + 
				"Gaines\n" + 
				"Galveston\n" + 
				"Garza\n" + 
				"Gillespie\n" + 
				"Glasscock\n" + 
				"Goliad\n" + 
				"Gonzales\n" + 
				"Gray\n" + 
				"Grayson\n" + 
				"Gregg\n" + 
				"Grimes\n" + 
				"Guadalupe\n" + 
				"Hale\n" + 
				"Hall\n" + 
				"Hamilton\n" + 
				"Hansford\n" + 
				"Hardeman\n" + 
				"Hardin\n" + 
				"Harris\n" + 
				"Harrison\n" + 
				"Hartley\n" + 
				"Haskell\n" + 
				"Hays\n" + 
				"Hemphill\n" + 
				"Henderson\n" + 
				"Hidalgo\n" + 
				"Hill\n" + 
				"Hockley\n" + 
				"Hood\n" + 
				"Hopkins\n" + 
				"Houston\n" + 
				"Howard\n" + 
				"Hudspeth\n" + 
				"Hunt\n" + 
				"Hutchinson\n" + 
				"Irion\n" + 
				"Jack\n" + 
				"Jackson\n" + 
				"Jasper\n" + 
				"Jeff Davis\n" + 
				"Jefferson\n" + 
				"Jim Hogg\n" + 
				"Jim Wells\n" + 
				"Johnson\n" + 
				"Jones\n" + 
				"Karnes\n" + 
				"Kaufman\n" + 
				"Kendall\n" + 
				"Kenedy\n" + 
				"Kent\n" + 
				"Kerr\n" + 
				"Kimble\n" + 
				"King\n" + 
				"Kinney\n" + 
				"Kleberg\n" + 
				"Knox\n" + 
				"Lamar\n" + 
				"Lamb\n" + 
				"Lampasas\n" + 
				"La Salle\n" + 
				"Lavaca\n" + 
				"Lee\n" + 
				"Leon\n" + 
				"Liberty\n" + 
				"Limestone\n" + 
				"Lipscomb\n" + 
				"Live Oak\n" + 
				"Llano\n" + 
				"Loving\n" + 
				"Lubbock\n" + 
				"Lynn\n" + 
				"McCulloch\n" + 
				"McLennan\n" + 
				"McMullen\n" + 
				"Madison\n" + 
				"Marion\n" + 
				"Martin\n" + 
				"Mason\n" + 
				"Matagorda\n" + 
				"Maverick\n" + 
				"Medina\n" + 
				"Menard\n" + 
				"Midland\n" + 
				"Milam\n" + 
				"Mills\n" + 
				"Mitchell\n" + 
				"Montague\n" + 
				"Montgomery\n" + 
				"Moore\n" + 
				"Morris\n" + 
				"Motley\n" + 
				"Nacogdoches\n" + 
				"Navarro\n" + 
				"Newton\n" + 
				"Nolan\n" + 
				"Nueces\n" + 
				"Ochiltree\n" + 
				"Oldham\n" + 
				"Orange\n" + 
				"Palo Pinto\n" + 
				"Panola\n" + 
				"Parker\n" + 
				"Parmer\n" + 
				"Pecos\n" + 
				"Polk\n" + 
				"Potter\n" + 
				"Presidio\n" + 
				"Rains\n" + 
				"Randall\n" + 
				"Reagan\n" + 
				"Real\n" + 
				"Red River\n" + 
				"Reeves\n" + 
				"Refugio\n" + 
				"Roberts\n" + 
				"Robertson\n" + 
				"Rockwall\n" + 
				"Runnels\n" + 
				"Rusk\n" + 
				"Sabine\n" + 
				"San Augustine\n" + 
				"San Jacinto\n" + 
				"San Patricio\n" + 
				"San Saba\n" + 
				"Schleicher\n" + 
				"Scurry\n" + 
				"Shackelford\n" + 
				"Shelby\n" + 
				"Sherman\n" + 
				"Smith\n" + 
				"Somervell\n" + 
				"Starr\n" + 
				"Stephens\n" + 
				"Sterling\n" + 
				"Stonewall\n" + 
				"Sutton\n" + 
				"Swisher\n" + 
				"Tarrant\n" + 
				"Taylor\n" + 
				"Terrell\n" + 
				"Terry\n" + 
				"Throckmorton\n" + 
				"Titus\n" + 
				"Tom Green\n" + 
				"Travis\n" + 
				"Trinity\n" + 
				"Tyler\n" + 
				"Upshur\n" + 
				"Upton\n" + 
				"Uvalde\n" + 
				"Val Verde\n" + 
				"Van Zandt\n" + 
				"Victoria\n" + 
				"Walker\n" + 
				"Waller\n" + 
				"Ward\n" + 
				"Washington\n" + 
				"Webb\n" + 
				"Wharton\n" + 
				"Wheeler\n" + 
				"Wichita\n" + 
				"Wilbarger\n" + 
				"Willacy\n" + 
				"Williamson\n" + 
				"Wilson\n" + 
				"Winkler\n" + 
				"Wise\n" + 
				"Wood\n" + 
				"Yoakum\n" + 
				"Young\n" + 
				"Zapata\n" + 
				"Zavala\n" + 
				"Beaver\n" + 
				"Box Elder\n" + 
				"Cache\n" + 
				"Carbon\n" + 
				"Daggett\n" + 
				"Davis\n" + 
				"Duchesne\n" + 
				"Emery\n" + 
				"Garfield\n" + 
				"Grand\n" + 
				"Iron\n" + 
				"Juab\n" + 
				"Kane\n" + 
				"Millard\n" + 
				"Morgan\n" + 
				"Piute\n" + 
				"Rich\n" + 
				"Salt Lake\n" + 
				"San Juan\n" + 
				"Sanpete\n" + 
				"Sevier\n" + 
				"Summit\n" + 
				"Tooele\n" + 
				"Uintah\n" + 
				"Utah\n" + 
				"Wasatch\n" + 
				"Washington\n" + 
				"Wayne\n" + 
				"Weber\n" + 
				"Addison\n" + 
				"Bennington\n" + 
				"Caledonia\n" + 
				"Chittenden\n" + 
				"Essex\n" + 
				"Franklin\n" + 
				"Grand Isle\n" + 
				"Lamoille\n" + 
				"Orange\n" + 
				"Orleans\n" + 
				"Rutland\n" + 
				"Washington\n" + 
				"Windham\n" + 
				"Windsor\n" + 
				"Accomack\n" + 
				"Amelia\n" + 
				"Amherst\n" + 
				"Appomattox\n" + 
				"Arlington\n" + 
				"Bath\n" + 
				"Bland\n" + 
				"Botetourt\n" + 
				"Brunswick\n" + 
				"Buchanan\n" + 
				"Buckingham\n" + 
				"Caroline\n" + 
				"Charles City\n" + 
				"Charlotte\n" + 
				"Chesterfield\n" + 
				"Clarke\n" + 
				"Craig\n" + 
				"Culpeper\n" + 
				"Cumberland\n" + 
				"Dickenson\n" + 
				"Fairfax\n" + 
				"Floyd\n" + 
				"Fluvanna\n" + 
				"Franklin\n" + 
				"Frederick\n" + 
				"Gloucester\n" + 
				"Goochland\n" + 
				"Grayson\n" + 
				"Greene\n" + 
				"Greensville\n" + 
				"Hanover\n" + 
				"Henrico\n" + 
				"Henry\n" + 
				"Isle of Wight\n" + 
				"James City\n" + 
				"King George\n" + 
				"King William\n" + 
				"Lancaster\n" + 
				"Lee\n" + 
				"Loudoun\n" + 
				"Louisa\n" + 
				"Lunenburg\n" + 
				"Madison\n" + 
				"Mathews\n" + 
				"Mecklenburg\n" + 
				"Middlesex\n" + 
				"Montgomery\n" + 
				"New Kent\n" + 
				"Northampton\n" + 
				"Northumberland\n" + 
				"Nottoway\n" + 
				"Orange\n" + 
				"Page\n" + 
				"Patrick\n" + 
				"Pittsylvania\n" + 
				"Prince Edward\n" + 
				"Prince George\n" + 
				"Rappahannock\n" + 
				"Richmond\n" + 
				"Roanoke\n" + 
				"Rockbridge\n" + 
				"Scott\n" + 
				"Shenandoah\n" + 
				"Smyth\n" + 
				"Southampton\n" + 
				"Sussex\n" + 
				"Tazewell\n" + 
				"Warren\n" + 
				"Washington\n" + 
				"Wise\n" + 
				"York\n" + 
				"Bedford\n" + 
				"Colonial Heights\n" + 
				"Fredericksburg\n" + 
				"Harrisonburg\n" + 
				"Norfolk\n" + 
				"Norton\n" + 
				"Radford\n" + 
				"Roanoke\n" + 
				"Salem\n" + 
				"Virginia Beach\n" + 
				"Waynesboro\n" + 
				"Adams\n" + 
				"Asotin\n" + 
				"Benton\n" + 
				"Chelan\n" + 
				"Clallam\n" + 
				"Clark\n" + 
				"Columbia\n" + 
				"Cowlitz\n" + 
				"Douglas\n" + 
				"Ferry\n" + 
				"Franklin\n" + 
				"Garfield\n" + 
				"Grant\n" + 
				"Grays Harbor\n" + 
				"Island\n" + 
				"Jefferson\n" + 
				"King\n" + 
				"Kitsap\n" + 
				"Kittitas\n" + 
				"Klickitat\n" + 
				"Lewis\n" + 
				"Lincoln\n" + 
				"Mason\n" + 
				"Okanogan\n" + 
				"Pacific\n" + 
				"Pend Oreille\n" + 
				"Pierce\n" + 
				"San Juan\n" + 
				"Skagit\n" + 
				"Skamania\n" + 
				"Snohomish\n" + 
				"Spokane\n" + 
				"Stevens\n" + 
				"Thurston\n" + 
				"Wahkiakum\n" + 
				"Walla Walla\n" + 
				"Whatcom\n" + 
				"Whitman\n" + 
				"Yakima\n" + 
				"Barbour\n" + 
				"Berkeley\n" + 
				"Boone\n" + 
				"Braxton\n" + 
				"Brooke\n" + 
				"Cabell\n" + 
				"Calhoun\n" + 
				"Clay\n" + 
				"Doddridge\n" + 
				"Fayette\n" + 
				"Gilmer\n" + 
				"Grant\n" + 
				"Greenbrier\n" + 
				"Hampshire\n" + 
				"Hancock\n" + 
				"Hardy\n" + 
				"Harrison\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Kanawha\n" + 
				"Lewis\n" + 
				"Lincoln\n" + 
				"Logan\n" + 
				"McDowell\n" + 
				"Marion\n" + 
				"Marshall\n" + 
				"Mason\n" + 
				"Mercer\n" + 
				"Mineral\n" + 
				"Mingo\n" + 
				"Monongalia\n" + 
				"Monroe\n" + 
				"Morgan\n" + 
				"Nicholas\n" + 
				"Ohio\n" + 
				"Pendleton\n" + 
				"Pleasants\n" + 
				"Pocahontas\n" + 
				"Preston\n" + 
				"Putnam\n" + 
				"Raleigh\n" + 
				"Randolph\n" + 
				"Ritchie\n" + 
				"Roane\n" + 
				"Summers\n" + 
				"Taylor\n" + 
				"Tucker\n" + 
				"Tyler\n" + 
				"Upshur\n" + 
				"Wayne\n" + 
				"Webster\n" + 
				"Wetzel\n" + 
				"Wirt\n" + 
				"Wood\n" + 
				"Wyoming\n" + 
				"Adams\n" + 
				"Ashland\n" + 
				"Barron\n" + 
				"Bayfield\n" + 
				"Brown\n" + 
				"Buffalo\n" + 
				"Burnett\n" + 
				"Calumet\n" + 
				"Chippewa\n" + 
				"Clark\n" + 
				"Columbia\n" + 
				"Crawford\n" + 
				"Dane\n" + 
				"Dodge\n" + 
				"Door\n" + 
				"Douglas\n" + 
				"Dunn\n" + 
				"Eau Claire\n" + 
				"Florence\n" + 
				"Fond du Lac\n" + 
				"Forest\n" + 
				"Grant\n" + 
				"Green\n" + 
				"Green Lake\n" + 
				"Iowa\n" + 
				"Iron\n" + 
				"Jackson\n" + 
				"Jefferson\n" + 
				"Juneau\n" + 
				"Kenosha\n" + 
				"Kewaunee\n" + 
				"La Crosse\n" + 
				"Lafayette\n" + 
				"Langlade\n" + 
				"Lincoln\n" + 
				"Manitowoc\n" + 
				"Marathon\n" + 
				"Marinette\n" + 
				"Marquette\n" + 
				"Menominee\n" + 
				"Milwaukee\n" + 
				"Monroe\n" + 
				"Oconto\n" + 
				"Oneida\n" + 
				"Outagamie\n" + 
				"Ozaukee\n" + 
				"Pepin\n" + 
				"Pierce\n" + 
				"Polk\n" + 
				"Portage\n" + 
				"Price\n" + 
				"Racine\n" + 
				"Richland\n" + 
				"Rock\n" + 
				"Rusk\n" + 
				"St. Croix\n" + 
				"Sauk\n" + 
				"Sawyer\n" + 
				"Shawano\n" + 
				"Sheboygan\n" + 
				"Taylor\n" + 
				"Trempealeau\n" + 
				"Vernon\n" + 
				"Vilas\n" + 
				"Walworth\n" + 
				"Washburn\n" + 
				"Washington\n" + 
				"Waukesha\n" + 
				"Waupaca\n" + 
				"Waushara\n" + 
				"Winnebago\n" + 
				"Wood\n" + 
				"Albany\n" + 
				"Big Horn\n" + 
				"Campbell\n" + 
				"Carbon\n" + 
				"Converse\n" + 
				"Crook\n" + 
				"Fremont\n" + 
				"Goshen\n" + 
				"Hot Springs\n" + 
				"Johnson\n" + 
				"Laramie\n" + 
				"Lincoln\n" + 
				"Natrona\n" + 
				"Niobrara\n" + 
				"Park\n" + 
				"Platte\n" + 
				"Sheridan\n" + 
				"Sublette\n" + 
				"Sweetwater\n" + 
				"Teton\n" + 
				"Uinta\n" + 
				"Washakie\n" + 
				"Weston\n" + 
				"Aleutians East Borough\n" + 
				"Aleutians West Census Area\n" + 
				"Anchorage Borough\n" + 
				"Bethel Census Area\n" + 
				"Bristol Bay Borough\n" + 
				"Denali Borough\n" + 
				"Dillingham Census Area\n" + 
				"Fairbanks North Star Borough\n" + 
				"Haines Borough\n" + 
				"Juneau Borough\n" + 
				"Kenai Peninsula Borough\n" + 
				"Ketchikan Gateway Borough\n" + 
				"Kodiak Island Borough\n" + 
				"Lake and Peninsula Borough\n" + 
				"Matanuska-Susitna Borough\n" + 
				"Nome Census Area\n" + 
				"North Slope Borough\n" + 
				"Northwest Arctic Borough\n" + 
				"Sitka Borough\n" + 
				"Southeast Fairbanks Census Area\n" + 
				"Valdez-Cordova Census Area\n" + 
				"Yakutat Borough\n" + 
				"Yukon-Koyukuk Census Area";
		
		String[] allCts = allCt.split("\n");
		return allCts;
	}
	
}